//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KindaView.h"

#import "MMKBankEditView-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"
#import "WCPaySelectBankViewControllerDelegate-Protocol.h"

@class MMKBankEditViewOnSeletBankCallback, NSMutableArray, NSString, UITextField, WCPaySelectBankViewController;

@interface KindaBankEditView : KindaView <WCPaySelectBankViewControllerDelegate, UITextFieldDelegate, MMKBankEditView>
{
    WCPaySelectBankViewController *m_selectBankVC;
    UITextField *m_view;
    NSMutableArray *m_bank_list;
    MMKBankEditViewOnSeletBankCallback *m_callback;
}

- (void).cxx_destruct;
- (void)setOnSeletBankCallback:(id)arg1;
- (void)OnWCPaySelectBankViewControllerDidSelectItem:(id)arg1;
- (void)OnGetWCPaySelectBankViewControllerDataSorce;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)setSelected:(id)arg1;
- (_Bool)getFocus;
- (void)setFocus:(_Bool)arg1;
- (void)setData:(id)arg1;
- (id)getView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

