//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MMWebViewProfileTitleModel : NSObject
{
    _Bool _isShow;
    _Bool _hasItemShowType;
    unsigned int _itemShowType;
    NSString *_brandIconUrl;
    NSString *_brandName;
    NSString *_brandDesc;
    NSString *_brandUserName;
    NSString *_pageTitle;
}

@property(nonatomic) _Bool hasItemShowType; // @synthesize hasItemShowType=_hasItemShowType;
@property(nonatomic) unsigned int itemShowType; // @synthesize itemShowType=_itemShowType;
@property(nonatomic) _Bool isShow; // @synthesize isShow=_isShow;
@property(copy, nonatomic) NSString *pageTitle; // @synthesize pageTitle=_pageTitle;
@property(copy, nonatomic) NSString *brandUserName; // @synthesize brandUserName=_brandUserName;
@property(copy, nonatomic) NSString *brandDesc; // @synthesize brandDesc=_brandDesc;
@property(copy, nonatomic) NSString *brandName; // @synthesize brandName=_brandName;
@property(copy, nonatomic) NSString *brandIconUrl; // @synthesize brandIconUrl=_brandIconUrl;
- (void).cxx_destruct;

@end

