//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WCStoryFriendCommmentHeadCellDelegate-Protocol.h"

@class NSMutableArray, NSString, UILabel, UITableView, WCStoryDataItem;
@protocol WCStoryFriendCommentCellDelegate;

@interface WCStoryFriendCommentCell : UICollectionViewCell <UITableViewDataSource, UITableViewDelegate, WCStoryFriendCommmentHeadCellDelegate>
{
    id <WCStoryFriendCommentCellDelegate> _delegate;
    WCStoryDataItem *_dataItem;
    NSMutableArray *_cellHeights;
    UITableView *_tableView;
    UILabel *_tipsLabel;
}

@property(retain, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSMutableArray *cellHeights; // @synthesize cellHeights=_cellHeights;
@property(retain, nonatomic) WCStoryDataItem *dataItem; // @synthesize dataItem=_dataItem;
@property(nonatomic) __weak id <WCStoryFriendCommentCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)StoryFriendCommmentHeadCellD:(id)arg1 didClickHeadViewWithComment:(id)arg2;
- (void)StoryFriendCommmentHeadCellD:(id)arg1 didClickBodyViewWithComment:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)handlePanGesture:(id)arg1;
- (void)setupGesture;
- (void)updateUI;
- (void)setupSubViews;
- (void)setup;
- (id)genCellHeightsWithDataItem:(id)arg1;
- (void)scrollViewToBottom;
- (void)reloadData;
- (void)scrollToBottom:(_Bool)arg1;
- (void)setTid:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

