//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/WXPBGeneratedMessage.h>

@class NSString;

@interface AppMsgContext : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int clientCacheTime; // @dynamic clientCacheTime;
@property(retain, nonatomic) NSString *content; // @dynamic content;
@property(retain, nonatomic) NSString *forceUrl; // @dynamic forceUrl;
@property(nonatomic) unsigned int lastModifyTime; // @dynamic lastModifyTime;
@property(nonatomic) _Bool noNeedUpdate; // @dynamic noNeedUpdate;
@property(nonatomic) unsigned int tmplVersion; // @dynamic tmplVersion;
@property(retain, nonatomic) NSString *url; // @dynamic url;

@end

