//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMMultiMenuTableViewCell.h"

@class UIView;

@interface FavMultiMenuTableViewCell : MMMultiMenuTableViewCell
{
    UIView *coverView;
    _Bool m_selected;
    UIView *_m_bkgCardView;
}

@property(retain, nonatomic) UIView *m_bkgCardView; // @synthesize m_bkgCardView=_m_bkgCardView;
- (void).cxx_destruct;
- (void)moreAction:(id)arg1;
- (void)showContentAction:(id)arg1;
- (void)deleteAction:(id)arg1;
- (void)forwardAction:(id)arg1;
- (void)setCoverView:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;

@end

