//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMObject.h>

#import "CNetworkStatusExt-Protocol.h"
#import "IFavoritesRepairSvrDataExt-Protocol.h"

@class FavoritesCDNInfoDB, FavoritesItemDB, NSMutableArray, NSString;

@interface FavoritesBaseUploadMgr : MMObject <IFavoritesRepairSvrDataExt, CNetworkStatusExt>
{
    _Bool _isUploading;
    _Bool _isCountingMd5;
    NSMutableArray *_uploadingQueue;
    NSMutableArray *_activeQueue;
    NSMutableArray *_failedQueue;
    FavoritesCDNInfoDB *_favCdnDB;
    FavoritesItemDB *_favItemDB;
}

@property(nonatomic) _Bool isCountingMd5; // @synthesize isCountingMd5=_isCountingMd5;
@property(retain, nonatomic) FavoritesItemDB *favItemDB; // @synthesize favItemDB=_favItemDB;
@property(retain, nonatomic) FavoritesCDNInfoDB *favCdnDB; // @synthesize favCdnDB=_favCdnDB;
@property(nonatomic) _Bool isUploading; // @synthesize isUploading=_isUploading;
@property(retain, nonatomic) NSMutableArray *failedQueue; // @synthesize failedQueue=_failedQueue;
@property(retain, nonatomic) NSMutableArray *activeQueue; // @synthesize activeQueue=_activeQueue;
@property(retain, nonatomic) NSMutableArray *uploadingQueue; // @synthesize uploadingQueue=_uploadingQueue;
- (void).cxx_destruct;
- (void)onRepairCheckFavItemAvailable:(unsigned int)arg1 occupied:(_Bool *)arg2;
- (void)ReachabilityChange:(unsigned int)arg1;
- (void)changeToNoWifi;
- (void)changeToWifi;
- (void)onUploadFail:(id)arg1 ErrCode:(int)arg2;
- (void)tryStartUpload;
- (void)checkAndTryStartUpload;
- (void)onCopyFileFinished:(id)arg1;
- (_Bool)doCopyFile:(id)arg1 withDataList:(id)arg2;
- (void)doCopyFile:(id)arg1;
- (_Bool)updateCdnInfo:(id)arg1 MD5:(id)arg2 Head256Md5:(id)arg3 Type:(int)arg4;
- (void)saveMd5ToCdnInfoTable:(id)arg1 withDataList:(id)arg2;
- (_Bool)CountItemDataMD5:(id)arg1 withDataList:(id)arg2;
- (_Bool)CountItemDataMD5:(id)arg1;
- (void)startCountMd5;
- (_Bool)addUploadDataList:(id)arg1 localId:(unsigned int)arg2 cdnStatus:(unsigned int)arg3;
- (void)dealloc;
- (void)initDB:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

