//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MCFilterManager, NSString;

@protocol MCFilterManagerDelegate <NSObject>

@optional
- (void)MCFilterManager:(MCFilterManager *)arg1 unsupportedMotionTmpl:(double)arg2 andMinCPULevel:(long long)arg3;
- (_Bool)MCFilterManager:(MCFilterManager *)arg1 motionTmplSelectFilter:(NSString *)arg2;
- (void)MCFilterManager:(MCFilterManager *)arg1 updateRecordingTimeSeconds:(double)arg2;
@end

