//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class MMTableViewCellInfo, MMUIView, UISwitch;

@interface MMTableViewCell : UITableViewCell
{
    UISwitch *m_switchAccessoryView;
    MMUIView *m_subContentView;
    MMTableViewCellInfo *_cellInfo;
    double _deselectDuration;
}

+ (id)getCellAttributeDetailTextHightlightedColor;
+ (id)getCellAttributeTextHightlightedColor;
+ (id)getCellTextHightlightedColor;
@property(nonatomic) double deselectDuration; // @synthesize deselectDuration=_deselectDuration;
@property(nonatomic) __weak MMTableViewCellInfo *cellInfo; // @synthesize cellInfo=_cellInfo;
@property(retain, nonatomic) MMUIView *m_subContentView; // @synthesize m_subContentView;
- (void).cxx_destruct;
- (long long)accessibilityElementCount;
- (void)addBackgroundView;
- (id)accessoryView;
- (void)setAccessoryView:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (void)setAccessoryType:(long long)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

