//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIWindow.h"

#import "CAAnimationDelegate-Protocol.h"
#import "CameraScanViewControllerExtention-Protocol.h"
#import "FullScreenViewControllerExtention-Protocol.h"
#import "IMMImagePickerManagerExt-Protocol.h"
#import "ISysCallCheckExt-Protocol.h"
#import "MMSightCameraExtention-Protocol.h"
#import "MMWebMiniMizeVCDelegate-Protocol.h"
#import "MsgFullScreenViewControllerExtention-Protocol.h"
#import "PhotoViewControllerExtention-Protocol.h"

@class MMWebMinimizeContext, MMWebMinimizeViewController, MMWebViewController, NSString;

@interface MMWebMinimizeWindow : MMUIWindow <MMWebMiniMizeVCDelegate, CAAnimationDelegate, PhotoViewControllerExtention, FullScreenViewControllerExtention, MsgFullScreenViewControllerExtention, CameraScanViewControllerExtention, IMMImagePickerManagerExt, MMSightCameraExtention, ISysCallCheckExt>
{
    _Bool _bAnimating;
    MMWebViewController *_webViewController;
    MMWebMinimizeViewController *_minimizeVC;
    MMWebMinimizeContext *_minimizationContext;
    struct CGPoint _beginMoveViewPoint;
}

+ (id)genMinimizationSessionId;
@property(nonatomic) struct CGPoint beginMoveViewPoint; // @synthesize beginMoveViewPoint=_beginMoveViewPoint;
@property(retain, nonatomic) MMWebMinimizeContext *minimizationContext; // @synthesize minimizationContext=_minimizationContext;
@property(nonatomic) _Bool bAnimating; // @synthesize bAnimating=_bAnimating;
@property(retain, nonatomic) MMWebMinimizeViewController *minimizeVC; // @synthesize minimizeVC=_minimizeVC;
@property(retain, nonatomic) MMWebViewController *webViewController; // @synthesize webViewController=_webViewController;
- (void).cxx_destruct;
- (void)OnSysCallState:(int)arg1 andCallId:(id)arg2;
- (void)applicationWillResignActive;
- (void)onMMImagePickerManagerShow;
- (void)onMMImagePickerManagerFinish;
- (void)CameraScanViewControllerDealloc;
- (void)CameraScanViewControllerWillBePoped;
- (void)CameraScanViewControllerWillBePushed;
- (void)MMSightCameraWillBePoped;
- (void)MMSightCameraWillBePushed;
- (void)MMSightCameraWillBeDismissed;
- (void)MMSightCameraWillBePresent;
- (void)msgFullScreenVCDealloc;
- (void)msgFullScrrenVCWillBePoped;
- (void)msgFullScreenVCWillBePushed;
- (void)msgFullScreenVCWillBeDismissed;
- (void)msgFullScreenVCWillBePresent;
- (void)fullScreenVCWillBeDismissed;
- (void)fullScreenVCWillBePresent;
- (void)PhotoViewControllerWillBeDismissed;
- (void)PhotoViewControllerWillBePresent;
- (void)PhotoViewControllerWillBePoped;
- (void)PhotoViewControllerWillBePushed;
- (id)webviewMinimizationContextLibraryPath;
- (void)removeCurrentMinimizationContext;
- (void)loadMinimizationContext;
- (_Bool)saveCurrentMinimizationContext;
- (struct CGPoint)moveViewDefaultPoint;
- (void)recoverWebViewController;
- (void)clearWebViewController;
- (void)minimizeWithWebViewController:(id)arg1;
- (void)configEndState;
- (void)hideCurrentWebVC:(id)arg1;
- (void)onBackgroundMoveViewMoveLong;
- (void)onBackgroundMoveViewBegin:(struct CGPoint)arg1;
- (void)onBackgroundMoveViewEndResultMoveTo:(struct CGPoint)arg1;
- (void)onBackgroundMoveViewMoveToRubish;
- (void)onBackgroundMoveViewTap;
- (void)setHidden:(_Bool)arg1;
- (void)becomeKeyWindow;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

