//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableDictionary.h>

@interface NSMutableDictionary (RTETextView)
- (void)applyStyleInverted:(_Bool)arg1 attributeName:(id)arg2 attributeValue:(id)arg3 font:(id)arg4;
- (void)removeListPrefixField;
- (void)removeAttachment;
@end

