//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "OpenSDKAuthorizeViewControllerInterface-Protocol.h"

@class NSString, OauthScopeInfo;
@protocol OpenSDKAuthorizeViewControllerDelegate;

@interface OpenSDKAuthorizeBaseViewController : MMUIViewController <OpenSDKAuthorizeViewControllerInterface>
{
    id <OpenSDKAuthorizeViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <OpenSDKAuthorizeViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onOAuthCancel;
- (id)navigationBarBackgroundColor;
- (void)viewDidLoad;

// Remaining properties
@property(retain, nonatomic) NSString *appName;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSString *iconUrl;
@property(retain, nonatomic) OauthScopeInfo *scopeInfo;
@property(readonly) Class superclass;

@end

