//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMMultiMenuTableViewCell.h"

@class CALayer, MMUILabel, MMWebImageView, OauthAvatarInfo, UIImageView;

@interface OpenSDKScopeUserInfoTableViewCell : MMMultiMenuTableViewCell
{
    MMWebImageView *_avatarImageView;
    MMUILabel *_nickNameLabel;
    MMUILabel *_descLabel;
    UIImageView *_selectImageView;
    CALayer *_topSeparateLine;
    CALayer *_bottomSeparateLine;
    _Bool _isSelect;
    _Bool _isBottom;
    OauthAvatarInfo *_avatarInfo;
}

+ (double)viewHeight;
@property(nonatomic) _Bool isBottom; // @synthesize isBottom=_isBottom;
@property(nonatomic) _Bool isSelect; // @synthesize isSelect=_isSelect;
@property(retain, nonatomic) OauthAvatarInfo *avatarInfo; // @synthesize avatarInfo=_avatarInfo;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)updateView;

@end

