//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface ReaderReporter : NSObject
{
    double _curOffset;
    NSMutableDictionary *_dicCards;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *dicCards; // @synthesize dicCards=_dicCards;
@property(nonatomic) double curOffset; // @synthesize curOffset=_curOffset;
- (void).cxx_destruct;
- (void)reportShowInfo;
- (void)onShowTitle:(id)arg1 Readers:(id)arg2;
- (_Bool)hadShowTitle:(id)arg1 WithReaders:(id)arg2;
- (void)checkShowWithText:(id)arg1 ReadersWraps:(id)arg2;
- (void)onTableDidScrollWithOffset:(double)arg1;
- (id)init;

@end

