//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface RTEAttachmentVideoInfo : NSObject
{
    unsigned int _dataSize;
    unsigned int _duration;
    int _status;
    double _width;
    double _height;
    NSString *_videoDataPath;
    NSString *_videoDataName;
    NSString *_videoDataMd5;
    NSString *_videothumbPath;
    NSString *_videoThumbName;
    NSString *_videoThumbMd5;
    NSString *_videoFmt;
    NSString *_desc;
    NSString *_videoUrl;
    NSString *_vid;
    double _progress;
}

@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(nonatomic) int status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *vid; // @synthesize vid=_vid;
@property(retain, nonatomic) NSString *videoUrl; // @synthesize videoUrl=_videoUrl;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString *videoFmt; // @synthesize videoFmt=_videoFmt;
@property(nonatomic) unsigned int duration; // @synthesize duration=_duration;
@property(retain, nonatomic) NSString *videoThumbMd5; // @synthesize videoThumbMd5=_videoThumbMd5;
@property(retain, nonatomic) NSString *videoThumbName; // @synthesize videoThumbName=_videoThumbName;
@property(retain, nonatomic) NSString *videothumbPath; // @synthesize videothumbPath=_videothumbPath;
@property(nonatomic) unsigned int dataSize; // @synthesize dataSize=_dataSize;
@property(retain, nonatomic) NSString *videoDataMd5; // @synthesize videoDataMd5=_videoDataMd5;
@property(retain, nonatomic) NSString *videoDataName; // @synthesize videoDataName=_videoDataName;
@property(retain, nonatomic) NSString *videoDataPath; // @synthesize videoDataPath=_videoDataPath;
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) double width; // @synthesize width=_width;
- (void).cxx_destruct;

@end

