//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSAttributedString, NSDictionary, NSMutableAttributedString;

@protocol RTEBaseFormatterProtocol <NSObject>

@optional
- (struct _NSRange)applicationRangeForRange:(struct _NSRange)arg1 inAttributedString:(NSAttributedString *)arg2;
- (_Bool)presentInAttributes:(NSDictionary *)arg1;
- (struct _NSRange)removeAttributesFromAttributedString:(NSMutableAttributedString *)arg1 atRange:(struct _NSRange)arg2;
- (struct _NSRange)applyAttributesToAttributedString:(NSMutableAttributedString *)arg1 atRange:(struct _NSRange)arg2;
- (NSDictionary *)removeFromAttributes:(NSDictionary *)arg1;
- (NSDictionary *)applyToAttributes:(NSDictionary *)arg1;
- (_Bool)presentInAttributedString:(NSAttributedString *)arg1 atIndex:(unsigned long long)arg2;
- (NSDictionary *)toggleInAttributes:(NSDictionary *)arg1;
- (struct _NSRange)toggleInAttributedString:(NSMutableAttributedString *)arg1 atRange:(struct _NSRange)arg2;
@end

