//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAttributedString, NSMutableDictionary, NSString;

@interface RTEHTMLBuilder : NSObject
{
    _Bool _useAppleConvertedSpace;
    NSAttributedString *_attributedString;
    NSString *_HTMLString;
    NSMutableDictionary *_styleLookup;
    NSString *_paragraphTagName;
}

+ (id)removeFirstNewLineCharacter:(id)arg1;
+ (id)removeLastNewLineCharacter:(id)arg1;
+ (id)convertParagraphsFromAttributedString:(id)arg1;
+ (id)webArchiveOfAttributedString:(id)arg1 escapeBlock:(CDUnknownBlockType)arg2;
+ (id)convertHtmlFromAttributedString:(id)arg1 escapeBlock:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) NSString *paragraphTagName; // @synthesize paragraphTagName=_paragraphTagName;
@property(nonatomic) _Bool useAppleConvertedSpace; // @synthesize useAppleConvertedSpace=_useAppleConvertedSpace;
@property(retain, nonatomic) NSMutableDictionary *styleLookup; // @synthesize styleLookup=_styleLookup;
@property(retain, nonatomic) NSString *HTMLString; // @synthesize HTMLString=_HTMLString;
@property(retain, nonatomic) NSAttributedString *attributedString; // @synthesize attributedString=_attributedString;
- (void).cxx_destruct;
- (id)tagRepresentationForTextList:(id)arg1 closingTag:(_Bool)arg2 listPadding:(double)arg3;
- (void)closeTextListWithWithEffectiveList:(id)arg1 previousLists:(id)arg2 currentLists:(id)arg3 retString:(id)arg4;
- (id)blockElementWithEffectiveList:(id)arg1 previousLists:(id)arg2 currentLists:(id)arg3 paragraphStyle:(id)arg4 paragraphRange:(struct _NSRange)arg5 retString:(id)arg6;
- (id)buildBlockElementStartTagWithElementName:(id)arg1 paraStyleString:(id)arg2 paragraphLevelHTMLAttributes:(id)arg3;
- (id)buildSpanElementWithEnumerationParagraphRange:(struct _NSRange)arg1 fontIsBlockLevel:(_Bool)arg2 plainText:(id)arg3;
- (void)buildOutputAsHTMLFragment;
- (id)htmlString;
- (id)styleClassForElement:(id)arg1 style:(id)arg2;
- (id)styleArrayForElement:(id)arg1;
- (id)initWithAttributedString:(id)arg1;

@end

