//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RTEHTMLNode.h"

@class NSString;

@interface RTEHTMLTextNode : RTEHTMLNode
{
    NSString *_charactes;
}

@property(readonly, nonatomic) NSString *charactes; // @synthesize charactes=_charactes;
- (void).cxx_destruct;
- (id)initWithCharacters:(id)arg1;

@end

