//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RTEParagraphProperty.h"

@interface RTEParagraphTextList : RTEParagraphProperty
{
    long long _style;
}

+ (long long)listStyleTypeFromString:(id)arg1;
+ (long long)styleOfCssStyle:(id)arg1;
+ (id)markerTextForStyle:(long long)arg1 andNumber:(unsigned long long)arg2;
@property(nonatomic) long long style; // @synthesize style=_style;
- (id)initWithStyle:(long long)arg1;

@end

