//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WALoadingViewController.h"

#import "IWALocalCacheMgrExt-Protocol.h"

@class UILabel, UIView;

@interface WAGameLoadingViewController : WALoadingViewController <IWALocalCacheMgrExt>
{
    UIView *_fakeNavBar;
    UIView *_backgroundView;
    UILabel *_progressLabel;
    UIView *m_menuView;
}

- (void).cxx_destruct;
- (void)startEnterAppAnimation;
- (void)onUpdateAppPkgComplete:(_Bool)arg1 withAppInfoData:(id)arg2 errorCode:(unsigned int)arg3 errorMsg:(id)arg4;
- (void)onUpdateAppPkgProgress:(float)arg1 remainingTime:(unsigned long long)arg2 totalLength:(unsigned long long)arg3 withAppInfoData:(id)arg4;
- (void)resetMenuView;
- (void)initRightMenu;
- (void)onReturn;
- (void)useExitLeftNavigationItem;
- (void)updateContact:(id)arg1;
- (void)dealloc;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithContact:(id)arg1 pagePath:(id)arg2;

@end

