//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCPayControlLogic.h"

#import "HoneyPayHomeControlLogicDelegate-Protocol.h"
#import "HoneyPayPayerDetailControlLogicDelegate-Protocol.h"
#import "WCBaseControlMgrExt-Protocol.h"
#import "WCPayLQTDetailControlLogicDelegate-Protocol.h"

@class JSEvent, NSString, WCPayBalanceFetchMoneyControlLogic, WCPayF2FJSApiAuthenticationControlLogic, WCPayF2FReceiveDetailControlLogic, WCPayJSApiAuthenticationControlLogic, WCPayJumpC2CMessageJsapiLogic, WCPayLQTDetailControlLogic, WCPayT2BCDetailControlLogic, WCPayT2BCTransferControlLogic;

@interface WCPayJSApiOpenWCPayViewControl : WCPayControlLogic <WCPayLQTDetailControlLogicDelegate, HoneyPayHomeControlLogicDelegate, HoneyPayPayerDetailControlLogicDelegate, WCBaseControlMgrExt>
{
    JSEvent *m_jsEvent;
    WCPayJSApiAuthenticationControlLogic *m_oAuthenticationLogic;
    int m_enWCPayCheckAuthorityScene;
    int m_enWCPayCheckOpenWCPayViewAuthorityScene;
    WCPayF2FJSApiAuthenticationControlLogic *_f2fJSApiAuthenControlLogic;
    WCPayF2FReceiveDetailControlLogic *_f2fDetailControlLogic;
    WCPayLQTDetailControlLogic *_lqtDetailControlLogic;
    WCPayT2BCDetailControlLogic *_t2bcDetailControlLogic;
    WCPayBalanceFetchMoneyControlLogic *_fetchBanlanceControlLogic;
    WCPayT2BCTransferControlLogic *_t2bcTransferControlLogic;
    WCPayJumpC2CMessageJsapiLogic *_m_jumpC2CMessageJsapiLogic;
}

@property(retain, nonatomic) WCPayJumpC2CMessageJsapiLogic *m_jumpC2CMessageJsapiLogic; // @synthesize m_jumpC2CMessageJsapiLogic=_m_jumpC2CMessageJsapiLogic;
@property(retain, nonatomic) WCPayT2BCTransferControlLogic *t2bcTransferControlLogic; // @synthesize t2bcTransferControlLogic=_t2bcTransferControlLogic;
@property(retain, nonatomic) WCPayBalanceFetchMoneyControlLogic *fetchBanlanceControlLogic; // @synthesize fetchBanlanceControlLogic=_fetchBanlanceControlLogic;
@property(retain, nonatomic) WCPayT2BCDetailControlLogic *t2bcDetailControlLogic; // @synthesize t2bcDetailControlLogic=_t2bcDetailControlLogic;
@property(retain, nonatomic) WCPayLQTDetailControlLogic *lqtDetailControlLogic; // @synthesize lqtDetailControlLogic=_lqtDetailControlLogic;
@property(retain, nonatomic) WCPayF2FReceiveDetailControlLogic *f2fDetailControlLogic; // @synthesize f2fDetailControlLogic=_f2fDetailControlLogic;
@property(retain, nonatomic) WCPayF2FJSApiAuthenticationControlLogic *f2fJSApiAuthenControlLogic; // @synthesize f2fJSApiAuthenControlLogic=_f2fJSApiAuthenControlLogic;
- (void).cxx_destruct;
- (void)honeyPayHomeLogicDidStop:(id)arg1;
- (void)onLQTDetailControlLogicStop;
- (void)callJSEventOKAndReport;
- (id)packageParam;
- (void)onWCBaseLogicDidStop:(unsigned int)arg1;
- (void)stopLogic;
- (void)dealloc;
- (void)startLogic;
- (id)initWithJSEvent:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

