//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCTTableCoding-Protocol.h"

@class NSString;

@interface DBContactMeta : NSObject <WCTTableCoding>
{
    unsigned int _lastUpdate;
    unsigned int _flag;
    unsigned int _intCon2;
    unsigned int _intCon3;
    NSString *_username;
    NSString *_strCon1;
    NSString *_strCon2;
    NSString *_strCon3;
}

+ (void)__wcdb_DBContactMeta_primary_48:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)strCon3;
+ (void)__wcdb_DBContactMeta_synthesize_47:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)strCon2;
+ (void)__wcdb_DBContactMeta_synthesize_46:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)strCon1;
+ (void)__wcdb_DBContactMeta_synthesize_45:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)intCon3;
+ (void)__wcdb_DBContactMeta_synthesize_44:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)intCon2;
+ (void)__wcdb_DBContactMeta_synthesize_43:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)flag;
+ (void)__wcdb_DBContactMeta_synthesize_42:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)lastUpdate;
+ (void)__wcdb_DBContactMeta_synthesize_41:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)username;
+ (void)__wcdb_DBContactMeta_synthesize_40:(struct WCTBinding *)arg1;
+ (CDUnknownBlockType)columnNamed;
+ (const struct All *)allResults;
+ (const struct WCTPropertyList *)allProperties;
+ (const struct WCTBinding *)objectRelationalMapping;
@property(retain, nonatomic) NSString *strCon3; // @synthesize strCon3=_strCon3;
@property(retain, nonatomic) NSString *strCon2; // @synthesize strCon2=_strCon2;
@property(retain, nonatomic) NSString *strCon1; // @synthesize strCon1=_strCon1;
@property(nonatomic) unsigned int intCon3; // @synthesize intCon3=_intCon3;
@property(nonatomic) unsigned int intCon2; // @synthesize intCon2=_intCon2;
@property(nonatomic) unsigned int flag; // @synthesize flag=_flag;
@property(nonatomic) unsigned int lastUpdate; // @synthesize lastUpdate=_lastUpdate;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
- (void).cxx_destruct;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

