//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCTTableCoding-Protocol.h"

@class NSString;

@interface FavoritesDownloadCDNInfo : NSObject <WCTTableCoding>
{
    unsigned int localItemId;
    unsigned int size;
    int status;
    int isThumb;
    int dataType;
    unsigned int IntRes1;
    unsigned int IntRes2;
    NSString *localDataID;
    NSString *cdnUrl;
    NSString *cdnKey;
    NSString *md5;
    NSString *head256Md5;
    NSString *dataFmt;
    NSString *favCheckId;
    NSString *StrRes1;
    NSString *StrRes2;
}

+ (void)__wcdb_FavoritesDownloadCDNInfo_index_51:(struct WCTBinding *)arg1;
+ (void)__wcdb_FavoritesDownloadCDNInfo_index_50:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)StrRes2;
+ (void)__wcdb_FavoritesDownloadCDNInfo_synthesize_49:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)StrRes1;
+ (void)__wcdb_FavoritesDownloadCDNInfo_synthesize_48:(struct WCTBinding *)arg1;
+ (void)__wcdb_FavoritesDownloadCDNInfo_default_47:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)IntRes2;
+ (void)__wcdb_FavoritesDownloadCDNInfo_synthesize_46:(struct WCTBinding *)arg1;
+ (void)__wcdb_FavoritesDownloadCDNInfo_default_45:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)IntRes1;
+ (void)__wcdb_FavoritesDownloadCDNInfo_synthesize_44:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)favCheckId;
+ (void)__wcdb_FavoritesDownloadCDNInfo_synthesize_43:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)dataFmt;
+ (void)__wcdb_FavoritesDownloadCDNInfo_synthesize_42:(struct WCTBinding *)arg1;
+ (void)__wcdb_FavoritesDownloadCDNInfo_default_41:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)dataType;
+ (void)__wcdb_FavoritesDownloadCDNInfo_synthesize_40:(struct WCTBinding *)arg1;
+ (void)__wcdb_FavoritesDownloadCDNInfo_default_39:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)isThumb;
+ (void)__wcdb_FavoritesDownloadCDNInfo_synthesize_38:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)head256Md5;
+ (void)__wcdb_FavoritesDownloadCDNInfo_synthesize_37:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)md5;
+ (void)__wcdb_FavoritesDownloadCDNInfo_synthesize_36:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)cdnKey;
+ (void)__wcdb_FavoritesDownloadCDNInfo_synthesize_35:(struct WCTBinding *)arg1;
+ (void)__wcdb_FavoritesDownloadCDNInfo_default_34:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)status;
+ (void)__wcdb_FavoritesDownloadCDNInfo_synthesize_33:(struct WCTBinding *)arg1;
+ (void)__wcdb_FavoritesDownloadCDNInfo_default_32:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)size;
+ (void)__wcdb_FavoritesDownloadCDNInfo_synthesize_31:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)cdnUrl;
+ (void)__wcdb_FavoritesDownloadCDNInfo_synthesize_30:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)localDataID;
+ (void)__wcdb_FavoritesDownloadCDNInfo_synthesize_29:(struct WCTBinding *)arg1;
+ (void)__wcdb_FavoritesDownloadCDNInfo_default_28:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)localItemId;
+ (void)__wcdb_FavoritesDownloadCDNInfo_synthesize_27:(struct WCTBinding *)arg1;
+ (CDUnknownBlockType)columnNamed;
+ (const struct All *)allResults;
+ (const struct WCTPropertyList *)allProperties;
+ (const struct WCTBinding *)objectRelationalMapping;
@property(retain, nonatomic) NSString *StrRes2; // @synthesize StrRes2;
@property(retain, nonatomic) NSString *StrRes1; // @synthesize StrRes1;
@property(nonatomic) unsigned int IntRes2; // @synthesize IntRes2;
@property(nonatomic) unsigned int IntRes1; // @synthesize IntRes1;
@property(retain, nonatomic) NSString *favCheckId; // @synthesize favCheckId;
@property(retain, nonatomic) NSString *dataFmt; // @synthesize dataFmt;
@property(nonatomic) int dataType; // @synthesize dataType;
@property(nonatomic) int isThumb; // @synthesize isThumb;
@property(retain, nonatomic) NSString *head256Md5; // @synthesize head256Md5;
@property(retain, nonatomic) NSString *md5; // @synthesize md5;
@property(retain, nonatomic) NSString *cdnKey; // @synthesize cdnKey;
@property(nonatomic) int status; // @synthesize status;
@property(nonatomic) unsigned int size; // @synthesize size;
@property(retain, nonatomic) NSString *cdnUrl; // @synthesize cdnUrl;
@property(retain, nonatomic) NSString *localDataID; // @synthesize localDataID;
@property(nonatomic) unsigned int localItemId; // @synthesize localItemId;
- (void).cxx_destruct;
- (id)init;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

