//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IMatrixCustomIssueExt-Protocol.h"

@class NSMutableArray, NSString;
@protocol crashReportConnectionDelegate;

@interface MMCrashReportConnection : NSObject <IMatrixCustomIssueExt>
{
    id <crashReportConnectionDelegate> _m_delegate;
    NSMutableArray *_wrapCrashArray;
}

@property(retain, nonatomic) NSMutableArray *wrapCrashArray; // @synthesize wrapCrashArray=_wrapCrashArray;
@property(nonatomic) __weak id <crashReportConnectionDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
- (void).cxx_destruct;
- (void)onCustomIssueUploadComplete:(_Bool)arg1 withReportKey:(id)arg2;
- (_Bool)uploadCrash:(id)arg1 reportType:(unsigned long long)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

