//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MMWebViewPreloadPageDataParameter : NSObject
{
    _Bool _isUsePreloadWebView;
    NSString *_url;
}

@property(nonatomic) _Bool isUsePreloadWebView; // @synthesize isUsePreloadWebView=_isUsePreloadWebView;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (id)description;

@end

