//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface RTEAttachmentImageInfo : NSObject
{
    unsigned int _dataSize;
    double _width;
    double _height;
    NSString *_bigImagePath;
    NSString *_thumbImagePath;
    NSString *_src;
    NSString *_desc;
}

@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString *src; // @synthesize src=_src;
@property(nonatomic) unsigned int dataSize; // @synthesize dataSize=_dataSize;
@property(retain, nonatomic) NSString *thumbImagePath; // @synthesize thumbImagePath=_thumbImagePath;
@property(retain, nonatomic) NSString *bigImagePath; // @synthesize bigImagePath=_bigImagePath;
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) double width; // @synthesize width=_width;
- (void).cxx_destruct;

@end

