//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/NSTextAttachment.h>

@class NSDictionary, NSURL, RTEAttachmentModel;

@interface RTETextAttachment : NSTextAttachment
{
    _Bool _bNeedSelectionWhenDelete;
    RTEAttachmentModel *_attachmentModel;
    NSURL *_contentURL;
    NSDictionary *_attributes;
    struct CGSize _size;
    struct CGSize _displaySize;
    struct CGSize _originalSize;
    struct UIEdgeInsets _contentInset;
}

+ (void)registerClass:(Class)arg1 forTagName:(id)arg2;
+ (id)generateAttachmentWithHTMLElement:(id)arg1 options:(id)arg2;
+ (Class)registeredClassForTagName:(id)arg1;
+ (void)initialize;
@property(nonatomic) struct CGSize originalSize; // @synthesize originalSize=_originalSize;
@property(nonatomic) struct CGSize displaySize; // @synthesize displaySize=_displaySize;
@property(retain, nonatomic) NSDictionary *attributes; // @synthesize attributes=_attributes;
@property(retain, nonatomic) NSURL *contentURL; // @synthesize contentURL=_contentURL;
@property(nonatomic) _Bool bNeedSelectionWhenDelete; // @synthesize bNeedSelectionWhenDelete=_bNeedSelectionWhenDelete;
@property(retain, nonatomic) RTEAttachmentModel *attachmentModel; // @synthesize attachmentModel=_attachmentModel;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(nonatomic) struct UIEdgeInsets contentInset; // @synthesize contentInset=_contentInset;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithHTMLElement:(id)arg1 options:(id)arg2;
- (id)init;

@end

