//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UISearchBar.h>

@interface WAMainFrameTaskBarSearchBar : UISearchBar
{
    _Bool _isChangeFrame;
    struct UIEdgeInsets _contentInset;
}

@property(nonatomic) _Bool isChangeFrame; // @synthesize isChangeFrame=_isChangeFrame;
@property(nonatomic) struct UIEdgeInsets contentInset; // @synthesize contentInset=_contentInset;
- (void)layoutSubviews;

@end

