//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MMCommon/MMService.h>

#import "MMService-Protocol.h"
#import "PBMessageObserverDelegate-Protocol.h"

@class NSMutableArray, NSString;

@interface WAPackageDownloadUrlFetcher : MMService <PBMessageObserverDelegate, MMService>
{
    NSMutableArray *_arrFetching;
    NSMutableArray *_arrWaiting;
}

- (void).cxx_destruct;
- (void)handleGetRemoteCDNPkgDownloadUrl:(id)arg1;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (_Bool)requestDownloadUrl:(id)arg1;
- (void)checkWaitingQueue;
- (void)removeInfoDataTask:(id)arg1;
- (_Bool)checkIsInQueue:(id)arg1 withInfoData:(id)arg2;
- (_Bool)checkIsInWaitingQueue:(id)arg1;
- (_Bool)checkIsInFetchQueue:(id)arg1;
- (void)mainThread_getRemoteCDNPkgDownloadUrlWithAppInfoData:(id)arg1;
- (void)getRemoteCDNPkgDownloadUrlWithAppInfoData:(id)arg1;
- (void)onServiceClearData;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

