//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AVAssetTrack.h"

@interface AVAssetTrack (SyncLoadAndGetParams)
- (id)syncGetParams:(id)arg1 timeout:(float)arg2;
- (id)syncGetParams:(id)arg1;
- (const struct AudioStreamBasicDescription *)syncGetAudioDescription;
- (float)syncGetFramerate;
- (float)syncGetBitrate;
@end

