//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class BrandProfileArticle, UILabel;

@interface BrandProfileTextCell : UITableViewCell
{
    UILabel *_titleLabel;
    BrandProfileArticle *_article;
}

+ (void)setPropertyOfTextLabel:(id)arg1 textString:(id)arg2 cellWidth:(double)arg3;
+ (double)cellHeight:(id)arg1 cellWidth:(double)arg2;
@property(retain, nonatomic) BrandProfileArticle *article; // @synthesize article=_article;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setupSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

