//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTReaderItemCellView.h"

#import "IAudioReceiverExt.h"
#import "IMusicPlayerExt.h"
#import "MMMusicPlayerContollerDelegate.h"
#import "MMUIViewControllerExt.h"

@class BTAudioItemCellViewModel, MMMusicPlayerContoller, MMUILabel, NSString, UIButton, UIImageView, UIView;

@interface BTAudioItemCellView : BTReaderItemCellView <MMUIViewControllerExt, IAudioReceiverExt, IMusicPlayerExt, MMMusicPlayerContollerDelegate>
{
    UIImageView *m_audioPlayView;
    UIButton *m_audioPlayButton;
    MMMusicPlayerContoller *m_audioPlayController;
    MMUILabel *m_timeLabel;
    UIView *m_containView;
}

- (void).cxx_destruct;
- (void)onClickToPlayMusic:(id)arg1 playState:(int)arg2;
- (void)onMusicPlayStatusChanged;
- (void)OnEndPlaying:(unsigned int)arg1 isForceStop:(_Bool)arg2;
- (void)MMUIViewControllerDidBeRemoved:(id)arg1;
- (id)getChatName:(id)arg1;
- (_Bool)playAudio;
- (void)StopPlay;
- (void)StartPlay;
- (void)onPlayBtnClick;
- (void)updateVoiceStatus;
- (void)layoutSubviewsNormalItem;
- (void)layoutSubviewsTopItem;
- (void)onUpdateViewModel;
- (void)initTitleAndTimeLabel;
- (void)initPlayView;
- (void)initNormalReaderItem;
- (void)initTopReaderItem;
- (id)initWithViewModel:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) BTAudioItemCellViewModel *viewModel; // @dynamic viewModel;

@end

