//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class CContact, MMHeadImageView, MMUILabel;

@interface BTOftenReadBarCollectionViewCell : UICollectionViewCell
{
    MMHeadImageView *_headImageView;
    MMUILabel *_nickNameLabel;
    CContact *_contact;
}

+ (double)itemHeight;
+ (double)itemWidth;
@property(retain, nonatomic) CContact *contact; // @synthesize contact=_contact;
@property(retain, nonatomic) MMUILabel *nickNameLabel; // @synthesize nickNameLabel=_nickNameLabel;
@property(retain, nonatomic) MMHeadImageView *headImageView; // @synthesize headImageView=_headImageView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)getCurrentContact;
- (void)updateContact:(id)arg1;
- (void)initNickNameLabel;
- (void)initHeaderView;
- (void)initView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

