//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@interface CashierSwitchInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) _Bool app; // @dynamic app;
@property(nonatomic) _Bool f2FHongbao; // @dynamic f2FHongbao;
@property(nonatomic) _Bool groupChatReceive; // @dynamic groupChatReceive;
@property(nonatomic) _Bool hongbao; // @dynamic hongbao;
@property(nonatomic) _Bool jsapi; // @dynamic jsapi;
@property(nonatomic) _Bool native; // @dynamic native;
@property(nonatomic) _Bool offline; // @dynamic offline;
@property(nonatomic) _Bool qrcodeReceive; // @dynamic qrcodeReceive;
@property(nonatomic) _Bool rewardCode; // @dynamic rewardCode;
@property(nonatomic) _Bool tinyapp; // @dynamic tinyapp;
@property(nonatomic) _Bool transfer; // @dynamic transfer;
@property(nonatomic) _Bool transfer2Bank; // @dynamic transfer2Bank;

@end

