//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@interface ConfDeviceParam : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int audioChannels; // @dynamic audioChannels;
@property(nonatomic) unsigned int audioSampleLenInms; // @dynamic audioSampleLenInms;
@property(nonatomic) unsigned int audioSampleRate; // @dynamic audioSampleRate;
@property(nonatomic) unsigned long long roomid; // @dynamic roomid;

@end

