//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCTTableCoding.h"

@class NSString;

@interface DBMessage : NSObject <WCTTableCoding>
{
    _Bool isAutoIncrement;
    unsigned int _version;
    unsigned int _msgLocalId;
    unsigned int _createTime;
    unsigned int _status;
    unsigned int _imageStatus;
    unsigned int _type;
    unsigned int _des;
    long long lastInsertedRowID;
    long long _msgServerId;
    NSString *_message;
}

+ (void)__wcdb_DBMessage_index_66:(struct WCTBinding *)arg1;
+ (void)__wcdb_DBMessage_index_65:(struct WCTBinding *)arg1;
+ (void)__wcdb_DBMessage_index_64:(struct WCTBinding *)arg1;
+ (void)__wcdb_DBMessage_primary_63:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)des;
+ (void)__wcdb_DBMessage_synthesize_62:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)type;
+ (void)__wcdb_DBMessage_synthesize_61:(struct WCTBinding *)arg1;
+ (void)__wcdb_DBMessage_default_60:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)imageStatus;
+ (void)__wcdb_DBMessage_synthesize_59:(struct WCTBinding *)arg1;
+ (void)__wcdb_DBMessage_default_58:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)status;
+ (void)__wcdb_DBMessage_synthesize_57:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)message;
+ (void)__wcdb_DBMessage_synthesize_56:(struct WCTBinding *)arg1;
+ (void)__wcdb_DBMessage_default_55:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)createTime;
+ (void)__wcdb_DBMessage_synthesize_54:(struct WCTBinding *)arg1;
+ (void)__wcdb_DBMessage_default_53:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)msgServerId;
+ (void)__wcdb_DBMessage_synthesize_52:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)msgLocalId;
+ (void)__wcdb_DBMessage_synthesize_51:(struct WCTBinding *)arg1;
+ (void)__wcdb_DBMessage_default_50:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)version;
+ (void)__wcdb_DBMessage_synthesize_49:(struct WCTBinding *)arg1;
+ (CDUnknownBlockType)columnNamed;
+ (const struct All *)allResults;
+ (const struct WCTPropertyList *)allProperties;
+ (const struct WCTBinding *)objectRelationalMapping;
@property(nonatomic) unsigned int des; // @synthesize des=_des;
@property(nonatomic) unsigned int type; // @synthesize type=_type;
@property(nonatomic) unsigned int imageStatus; // @synthesize imageStatus=_imageStatus;
@property(nonatomic) unsigned int status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(nonatomic) unsigned int createTime; // @synthesize createTime=_createTime;
@property(nonatomic) long long msgServerId; // @synthesize msgServerId=_msgServerId;
@property(nonatomic) unsigned int msgLocalId; // @synthesize msgLocalId=_msgLocalId;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
@property(nonatomic) long long lastInsertedRowID; // @synthesize lastInsertedRowID;
@property(nonatomic) _Bool isAutoIncrement; // @synthesize isAutoIncrement;
- (void).cxx_destruct;

@end

