//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIViewController;

@protocol EditImageInitialViewDelegate <NSObject>
- (UIViewController *)currentViewController;
- (void)getOriginalImage:(void (^)(UIImage *, NSData *))arg1;
- (void)getDisplayImage:(void (^)(UIImage *, NSMutableArray *, _Bool))arg1;
- (void)OnClickEditImageDoneBarButton;
- (void)OnClickEditImageBackBarButton;
@end

