//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "UIScrollViewDelegate.h"

@class FaceRecogGuideInfo, MMUILabel, NSString, UIButton, UIImageView, UIScrollView, UIView;

@interface FaceRecogReadNumGuideView : MMUIView <UIScrollViewDelegate>
{
    UIScrollView *_pageScrollView;
    MMUILabel *_guideTitleLabel;
    UIImageView *_firstStepNumberIconView;
    MMUILabel *_firstStepContentLabel;
    UIImageView *_firstStepIconView;
    UIImageView *_secondStepNumberIconView;
    MMUILabel *_secondStepContentLabel;
    UIImageView *_secondStepIconView;
    UIButton *_finishBtn;
    UIView *_connectLineView;
    FaceRecogGuideInfo *_guideInfo;
    id <FaceRecogGuideViewDelegate> _delegate;
}

@property(nonatomic) __weak id <FaceRecogGuideViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) FaceRecogGuideInfo *guideInfo; // @synthesize guideInfo=_guideInfo;
@property(retain, nonatomic) UIView *connectLineView; // @synthesize connectLineView=_connectLineView;
@property(retain, nonatomic) UIButton *finishBtn; // @synthesize finishBtn=_finishBtn;
@property(retain, nonatomic) UIImageView *secondStepIconView; // @synthesize secondStepIconView=_secondStepIconView;
@property(retain, nonatomic) MMUILabel *secondStepContentLabel; // @synthesize secondStepContentLabel=_secondStepContentLabel;
@property(retain, nonatomic) UIImageView *secondStepNumberIconView; // @synthesize secondStepNumberIconView=_secondStepNumberIconView;
@property(retain, nonatomic) UIImageView *firstStepIconView; // @synthesize firstStepIconView=_firstStepIconView;
@property(retain, nonatomic) MMUILabel *firstStepContentLabel; // @synthesize firstStepContentLabel=_firstStepContentLabel;
@property(retain, nonatomic) UIImageView *firstStepNumberIconView; // @synthesize firstStepNumberIconView=_firstStepNumberIconView;
@property(retain, nonatomic) MMUILabel *guideTitleLabel; // @synthesize guideTitleLabel=_guideTitleLabel;
@property(retain, nonatomic) UIScrollView *pageScrollView; // @synthesize pageScrollView=_pageScrollView;
- (void).cxx_destruct;
- (void)initData;
- (void)initLineView;
- (void)initFirstPage;
- (void)initScrollView;
- (void)initView;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

