//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AccountBaseViewController.h"

#import "IMMFacebookMgrExt.h"
#import "UIAlertViewDelegate.h"

@class MMTableViewInfo, NSString, UIButton;

@interface FacebookViewController : AccountBaseViewController <IMMFacebookMgrExt, UIAlertViewDelegate>
{
    UIButton *m_bindBtn;
    UIButton *m_unBindBtn;
    UIButton *m_doneBtn;
    MMTableViewInfo *m_tableViewInfo;
    id <FacebookViewControllerDelegate> m_delegate;
}

@property(nonatomic) __weak id <FacebookViewControllerDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (void)onUnBindFacebookFinish:(unsigned int)arg1;
- (void)onBindFacebookFinish:(unsigned int)arg1;
- (void)autoDismis;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onUnbind;
- (void)done;
- (void)onUnBindAccount;
- (void)bind;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)updateTableCell;
- (void)initFooterView;
- (void)initHeaderView;
- (void)dealloc;
- (void)disMiss;
- (void)updateView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

