//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class FavoritesItem, NSMutableArray;

@interface FavoritesUploadBaseProccessor : MMObject
{
    NSMutableArray *m_proccessingQueue;
    _Bool m_bProccessing;
    FavoritesItem *m_priorItem;
    FavoritesItem *m_proccessingItem;
    FavoritesUploadBaseProccessor *nextProccessor;
    id <FavoritesUploadProccessorDelegate> _delegate;
}

@property(nonatomic) __weak id <FavoritesUploadProccessorDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak FavoritesUploadBaseProccessor *nextProccessor; // @synthesize nextProccessor;
- (void).cxx_destruct;
- (void)removeAllItems;
- (_Bool)checkFavItemOccupiedByFavId:(unsigned int)arg1;
- (_Bool)isProccessingWithLocalId:(unsigned int)arg1;
- (void)removeItem:(id)arg1;
- (void)addItem:(id)arg1 isPrior:(_Bool)arg2;
- (void)dealloc;
- (void)tryProccess;
- (void)triggerProccess;
- (id)initWithDelegate:(id)arg1;

@end

