//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FixDocumentPresent : NSObject
{
    _Bool _fixDocumentVCDismissBugFlag;
    _Bool _shouldFixThisProblem;
}

@property(nonatomic) _Bool shouldFixThisProblem; // @synthesize shouldFixThisProblem=_shouldFixThisProblem;
@property(nonatomic) _Bool fixDocumentVCDismissBugFlag; // @synthesize fixDocumentVCDismissBugFlag=_fixDocumentVCDismissBugFlag;
- (_Bool)shouldDismissViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)recordPresentViewController:(id)arg1;
- (id)init;

@end

