//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSString, RelevantSearchResult;

@interface FTSSearchLocalPageResultWrap : MMObject
{
    NSString *_fromQuery;
    RelevantSearchResult *_relevantResult;
    NSString *_searchId;
}

@property(retain, nonatomic) NSString *searchId; // @synthesize searchId=_searchId;
@property(retain, nonatomic) RelevantSearchResult *relevantResult; // @synthesize relevantResult=_relevantResult;
@property(retain, nonatomic) NSString *fromQuery; // @synthesize fromQuery=_fromQuery;
- (void).cxx_destruct;
- (id)genWordConcatStr;
- (_Bool)isValid;

@end

