//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FTSUtil : NSObject
{
}

+ (unsigned int)CalMMContactCountForGroupContact:(id)arg1 dicCache:(id)arg2;
+ (unsigned int)ConvertClickTypeFromFeedType:(unsigned int)arg1;
+ (id)encryptForLog:(id)arg1;
+ (double)getSearchCancelButtonWidth;
+ (void)commonSearchClickReport:(id)arg1;
+ (id)FTSOpenIMAppIdLogFromContact:(id)arg1;
+ (id)getFTSDBPath;
+ (id)getUserFTSRootDir;

@end

