//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray;

@protocol IExptServiceExt

@optional
- (void)updateWCLabByXExpt:(NSArray *)arg1 deleteExptIds:(NSArray *)arg2 andExptFlag:(unsigned int)arg3 andAppIdList:(NSArray *)arg4;
- (void)onExptItemListChange;
@end

