//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IRegisterableCallbackHolder : NSObject
{
    CDUnknownBlockType callback;
    _Bool isContinuous;
}

@property(nonatomic) _Bool isContinuous; // @synthesize isContinuous;
@property(copy) CDUnknownBlockType callback; // @synthesize callback;
- (void).cxx_destruct;
- (id)initWithCallback:(CDUnknownBlockType)arg1 isContinuous:(_Bool)arg2;

@end

