//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RTETextAttachment.h"

#import "IQQMailExt.h"

@class MailRTEAttachmentInfo, NSString;

@interface MailRTEAttachment : RTETextAttachment <IQQMailExt>
{
    unsigned int _type;
    unsigned int _subType;
    unsigned int _dataStatus;
    NSString *_objectId;
    NSString *_objectName;
    MailRTEAttachmentInfo *_attachmentInfo;
}

@property(retain, nonatomic) MailRTEAttachmentInfo *attachmentInfo; // @synthesize attachmentInfo=_attachmentInfo;
@property(nonatomic) unsigned int dataStatus; // @synthesize dataStatus=_dataStatus;
@property(nonatomic) unsigned int subType; // @synthesize subType=_subType;
@property(nonatomic) unsigned int type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *objectName; // @synthesize objectName=_objectName;
@property(retain, nonatomic) NSString *objectId; // @synthesize objectId=_objectId;
- (void).cxx_destruct;
- (void)OnUploadData:(id)arg1 filename:(id)arg2 ErrNo:(int)arg3;
- (double)getHeightOfAttachment;
- (id)createThumbImage:(id)arg1;
- (id)UIImageWriteToTempFile:(id)arg1;
- (_Bool)isGifAttachment;
- (id)getTempFilePath;
- (id)UIImageDataWriteToTempFile:(id)arg1;
- (id)getThumbPath;
- (id)getDataPath;
- (void)configAttachmentWithHr;
- (void)configAttachmentWithLocation:(id)arg1;
- (void)configAttachmentWithAsset:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)configAttachmentWithGifData:(id)arg1;
- (void)configAttachmentWithImage:(id)arg1;
- (struct CGRect)attachmentBoundsForTextContainer:(id)arg1 proposedLineFragment:(struct CGRect)arg2 glyphPosition:(struct CGPoint)arg3 characterIndex:(unsigned long long)arg4;
- (void)dealloc;
- (id)init;

@end

