//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIView;

@protocol MainTableDelegate <NSObject>
- (double)getContentViewY;
- (double)getMainTableBottomInset;
- (double)getMainTableHeight;

@optional
- (unsigned long long)handleTouchesShouldCancelInContentView:(UIView *)arg1;
@end

