//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMKView.h"

@class NSString;

@protocol MMKLabelView <MMKView>
- (int)getMaxLength;
- (void)setMaxLength:(int)arg1;
- (long long)getTextAlign;
- (void)setTextAlign:(long long)arg1;
- (long long)getEllipsize;
- (void)setEllipsize:(long long)arg1;
- (long long)getFontStyle;
- (void)setFontStyle:(long long)arg1;
- (NSString *)getTextFont;
- (void)setTextFont:(NSString *)arg1;
- (long long)getTextColor;
- (void)setTextColor:(long long)arg1;
- (float)getTextSize;
- (void)setTextSize:(float)arg1;
- (NSString *)getText;
- (void)setText:(NSString *)arg1;
- (int)getLines;
- (void)setLines:(int)arg1;
@end

