//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol MMResourceDownloader <NSObject>
@property(retain, nonatomic) NSString *downloadIdentifier;
@property(nonatomic) __weak id <MMResourceDownloadDelegate> downloadDelegate;
- (void)clearData;
- (void)cancel;
- (void)start;
- (id)initWithUrl:(NSString *)arg1;
@end

