//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "WCTTableCoding.h"

@class MMResDownloadUrlInfo, NSString;

@interface MMResDownloadInfo : MMObject <WCTTableCoding>
{
    unsigned int resType;
    unsigned int networkType;
    unsigned int scene;
    unsigned int expiredTime;
    unsigned int subType;
    unsigned int retryTime;
    unsigned int reportId;
    unsigned int eid;
    NSString *appId;
    NSString *domain;
    NSString *baseDir;
    NSString *sampleId;
    NSString *packageId;
    MMResDownloadUrlInfo *resUrlInfo;
}

+ (const struct WCTProperty *)eid;
+ (void)__wcdb_MMResDownloadInfo_synthesize_42:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)resUrlInfo;
+ (void)__wcdb_MMResDownloadInfo_synthesize_41:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)packageId;
+ (void)__wcdb_MMResDownloadInfo_synthesize_40:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)sampleId;
+ (void)__wcdb_MMResDownloadInfo_synthesize_39:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)reportId;
+ (void)__wcdb_MMResDownloadInfo_synthesize_38:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)retryTime;
+ (void)__wcdb_MMResDownloadInfo_synthesize_37:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)baseDir;
+ (void)__wcdb_MMResDownloadInfo_synthesize_36:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)domain;
+ (void)__wcdb_MMResDownloadInfo_synthesize_35:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)appId;
+ (void)__wcdb_MMResDownloadInfo_synthesize_34:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)subType;
+ (void)__wcdb_MMResDownloadInfo_synthesize_33:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)expiredTime;
+ (void)__wcdb_MMResDownloadInfo_synthesize_32:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)scene;
+ (void)__wcdb_MMResDownloadInfo_synthesize_31:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)networkType;
+ (void)__wcdb_MMResDownloadInfo_synthesize_30:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)resType;
+ (void)__wcdb_MMResDownloadInfo_synthesize_29:(struct WCTBinding *)arg1;
+ (CDUnknownBlockType)columnNamed;
+ (const struct All *)allResults;
+ (const struct WCTPropertyList *)allProperties;
+ (const struct WCTBinding *)objectRelationalMapping;
@property(nonatomic) unsigned int eid; // @synthesize eid;
@property(retain, nonatomic) MMResDownloadUrlInfo *resUrlInfo; // @synthesize resUrlInfo;
@property(retain, nonatomic) NSString *packageId; // @synthesize packageId;
@property(retain, nonatomic) NSString *sampleId; // @synthesize sampleId;
@property(nonatomic) unsigned int reportId; // @synthesize reportId;
@property(nonatomic) unsigned int retryTime; // @synthesize retryTime;
@property(retain, nonatomic) NSString *baseDir; // @synthesize baseDir;
@property(retain, nonatomic) NSString *domain; // @synthesize domain;
@property(retain, nonatomic) NSString *appId; // @synthesize appId;
@property(nonatomic) unsigned int subType; // @synthesize subType;
@property(nonatomic) unsigned int expiredTime; // @synthesize expiredTime;
@property(nonatomic) unsigned int scene; // @synthesize scene;
@property(nonatomic) unsigned int networkType; // @synthesize networkType;
@property(nonatomic) unsigned int resType; // @synthesize resType;
- (void).cxx_destruct;
- (void)dealloc;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

