//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol MMWebBackgroundMoveViewDelegate <NSObject>
- (void)onBackgroundMoveViewTap;

@optional
- (void)onBackgroundMoveViewLongPress;
- (void)onBackgroundMoveViewEndResultMoveTo:(struct CGPoint)arg1;
- (void)onBackgroundMoveViewEnd:(struct CGPoint)arg1;
- (void)onBackgroundMoveViewMoveTo:(struct CGPoint)arg1;
- (void)onBackgroundMoveViewMoveOutOffScreen;
- (void)onBackgroundMoveViewMoveLong;
- (void)onBackgroundMoveViewBegin:(struct CGPoint)arg1;
@end

