//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSScanner.h"

@interface NSScanner (SVGExtend)
+ (id)complementaryCharacterSetFromWhitespaceAndNewline;
+ (id)whitespaceCommasAndClosingParenthesisCharacterSet;
+ (id)complementaryCharacterSetFromNumber;
- (_Bool)scanCGFloat:(double *)arg1;
- (_Bool)scanBool:(_Bool *)arg1;
- (_Bool)scanPoint:(struct CGPoint *)arg1;
- (void)scanThroughToHyphen;
- (unsigned short)currentCharacter;
- (unsigned short)initialCharacter;
- (void)scanThroughWhitespaceCommasAndClosingParenthesis;
- (_Bool)scanFloatAndAdvance:(float *)arg1;
@end

