//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol OpenSDKAuthorizeViewControllerDelegate <NSObject>
- (void)onScopeViewControllerClose:(id <OpenSDKAuthorizeViewControllerInterface>)arg1;
- (void)onScopeViewControllerDeny:(id <OpenSDKAuthorizeViewControllerInterface>)arg1;
- (void)onScopeViewControllerConfirm:(id <OpenSDKAuthorizeViewControllerInterface>)arg1;
@end

