//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "OpenSDKAuthorizeViewControllerInterface.h"

@class NSString, OauthScopeInfo, UIScrollView;

@interface OpenSDKAuthorizeFriendsViewController : MMUIViewController <OpenSDKAuthorizeViewControllerInterface>
{
    NSString *_appName;
    NSString *_iconUrl;
    OauthScopeInfo *_scopeInfo;
    id <OpenSDKAuthorizeViewControllerDelegate> _delegate;
    UIScrollView *_scrollView;
}

@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak id <OpenSDKAuthorizeViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) OauthScopeInfo *scopeInfo; // @synthesize scopeInfo=_scopeInfo;
@property(retain, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
@property(retain, nonatomic) NSString *appName; // @synthesize appName=_appName;
- (void).cxx_destruct;
- (void)onDenyBtnClick;
- (void)onComfirmBtnClick;
- (void)initSubViews;
- (_Bool)interactivePopGestureRecognizerShouldBegin:(id)arg1;
- (void)onReturn;
- (void)initNavigationBar;
- (id)navigationBarBackgroundColor;
- (void)viewDidLoad;
- (id)initWithAppName:(id)arg1 iconUrl:(id)arg2 scopeInfo:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

