//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "CSettingExt.h"
#import "HDHeadImageViewDelegate.h"
#import "IMyInvoiceLogicMgrExt.h"
#import "IOplogExt.h"
#import "settingModifyAliasDelegate.h"
#import "settingMyAccountExtInfoLogicDelegate.h"

@class MMHeadImageView, NSString, NameEditorViewController, WCTableViewManager;

@interface SettingMyProfileViewController : MMUIViewController <HDHeadImageViewDelegate, settingMyAccountExtInfoLogicDelegate, CSettingExt, settingModifyAliasDelegate, IOplogExt, IMyInvoiceLogicMgrExt>
{
    MMHeadImageView *m_headImage;
    NameEditorViewController *m_CurrentVC;
    NSString *m_nsTempNickName;
    _Bool m_bHaveInvoiceInfo;
    WCTableViewManager *m_tableViewMgr;
}

- (void).cxx_destruct;
- (void)viewDidTransitionToNewSize;
- (void)initDeepLinkConfig;
- (void)oplogRet:(int)arg1 errMsg:(id)arg2 eventID:(unsigned int)arg3 cgiWrap:(id)arg4;
- (void)onModifyNickName:(id)arg1 vc:(id)arg2;
- (void)onSettingChanged:(int)arg1;
- (void)onInfoChange;
- (void)DeleteInvoiceInfo:(unsigned int)arg1;
- (void)SaveInvoiceInfo:(id)arg1;
- (void)OnGetInvoiceRet:(_Bool)arg1 andResult:(id)arg2 fromScene:(unsigned int)arg3;
- (void)dealloc;
- (void)showSocialInfo;
- (void)showInvoiceView;
- (void)showMyAddressInfoView;
- (void)showQRInfoView;
- (void)showModifyNickName;
- (void)makeChangeImgCell:(id)arg1;
- (void)willAppear;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)onChangeImg:(id)arg1;
- (void)updateHead:(id)arg1;
- (id)getSettingHeadImage;
- (void)updateTableCell;
- (void)saveNewAlias;
- (void)showModifyUserName;
- (_Bool)isNeedShowWCPay;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

