//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface StoryCommentInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) int commentId; // @dynamic commentId;
@property(retain, nonatomic) NSString *content; // @dynamic content;
@property(nonatomic) unsigned int createTime; // @dynamic createTime;
@property(nonatomic) unsigned int deleteFlag; // @dynamic deleteFlag;
@property(nonatomic) unsigned int isNotRichText; // @dynamic isNotRichText;
@property(nonatomic) int replyCommentId; // @dynamic replyCommentId;
@property(retain, nonatomic) NSString *replyUserName; // @dynamic replyUserName;
@property(retain, nonatomic) NSString *userName; // @dynamic userName;

@end

