//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class NSString, TriangleView, UIView;

@interface WAGameLoadingAnimateView : MMUIView
{
    float _currentProgress;
    UIView *_greenLoopView1;
    UIView *_greenLoopView2;
    TriangleView *_triangle;
    NSString *_progressBarColor;
}

@property(retain, nonatomic) NSString *progressBarColor; // @synthesize progressBarColor=_progressBarColor;
@property(retain, nonatomic) TriangleView *triangle; // @synthesize triangle=_triangle;
@property(nonatomic) float currentProgress; // @synthesize currentProgress=_currentProgress;
@property(retain, nonatomic) UIView *greenLoopView2; // @synthesize greenLoopView2=_greenLoopView2;
@property(retain, nonatomic) UIView *greenLoopView1; // @synthesize greenLoopView1=_greenLoopView1;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)endLoadingAnimation;
- (void)beginLoadingAnimation;
- (void)updateProgress:(float)arg1;
- (void)setupLoadingView;
- (id)initWithFrame:(struct CGRect)arg1 progressBarColor:(id)arg2;

@end

