//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "WAMainFrameTaskBarCollectionViewLayoutDelegate.h"
#import "WAMainFrameTaskItemMgrExt.h"

@class MMDynamicItem, MMUIViewController, NSMutableArray, NSString, UIAttachmentBehavior, UIButton, UICollectionView, UIDynamicAnimator, UIImage, UIImageView, UILabel, UILongPressGestureRecognizer, WAMainFrameTaskBarCollectionViewLayout, WAMainFrameTaskBarDotLoadingView, WAMainFrameTaskBarLogic;

@interface WAMainFrameTaskBarView : UIView <WAMainFrameTaskItemMgrExt, UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, WAMainFrameTaskBarCollectionViewLayoutDelegate>
{
    _Bool m_isLayouted;
    NSMutableArray *m_arrMenuItems;
    _Bool m_isContentViewAnimating;
    _Bool _isNeedMoreButton;
    _Bool _containerVCDisappearing;
    _Bool _draggingShowState;
    _Bool _visibleReachEnd;
    _Bool _tapTicState;
    _Bool _whyPullMeShowState;
    _Bool _reseted;
    id <WAMainFrameTaskBarViewDelegate> _taskBarViewDelegate;
    MMUIViewController *_containerVC;
    UIView *_fakeNavigationBottomBackground;
    UIView *_fakeNavigationBackground;
    UIView *_backgroundView;
    UIView *_contentView;
    UIView *_topMarginView;
    UILabel *_taskTitleLabel;
    UIImageView *_taskTitleArrow;
    UIButton *_taskTitleButton;
    UICollectionView *_taskCollectionView;
    WAMainFrameTaskBarCollectionViewLayout *_taskCollectionViewLayout;
    UIView *_gapMarginView;
    UILabel *_starTitleLabel;
    UIImageView *_starTitleArrow;
    UIButton *_starTitleButton;
    UICollectionView *_starCollectionView;
    WAMainFrameTaskBarCollectionViewLayout *_starCollectionViewLayout;
    UIView *_emptyView;
    UIImageView *_emptyLogo;
    UILabel *_emptyTips;
    WAMainFrameTaskBarDotLoadingView *_arrowImageView;
    UILabel *_whyPullMeTipsLabel;
    UILongPressGestureRecognizer *_longPressGestureOnTaskCollectionView;
    UILongPressGestureRecognizer *_longPressGestureOnStarCollectionView;
    WAMainFrameTaskBarLogic *_taskBarLogic;
    UIImage *_animateGif;
    double _lastVisibleOffsetY;
    double _lastLoadingImageVisibleOffsetY;
    double _lastStickingOffsetY;
    double _lastVisibleBackgroundOffsetY;
    UIDynamicAnimator *_taskAnimator;
    MMDynamicItem *_taskDynamicItem;
    UIAttachmentBehavior *_taskSpringBehavior;
    UIDynamicAnimator *_starAnimator;
    MMDynamicItem *_starDynamicItem;
    UIAttachmentBehavior *_starSpringBehavior;
    struct CGPoint _startContentOffset;
}

@property(nonatomic) __weak UIAttachmentBehavior *starSpringBehavior; // @synthesize starSpringBehavior=_starSpringBehavior;
@property(retain, nonatomic) MMDynamicItem *starDynamicItem; // @synthesize starDynamicItem=_starDynamicItem;
@property(retain, nonatomic) UIDynamicAnimator *starAnimator; // @synthesize starAnimator=_starAnimator;
@property(nonatomic) __weak UIAttachmentBehavior *taskSpringBehavior; // @synthesize taskSpringBehavior=_taskSpringBehavior;
@property(retain, nonatomic) MMDynamicItem *taskDynamicItem; // @synthesize taskDynamicItem=_taskDynamicItem;
@property(retain, nonatomic) UIDynamicAnimator *taskAnimator; // @synthesize taskAnimator=_taskAnimator;
@property(nonatomic) struct CGPoint startContentOffset; // @synthesize startContentOffset=_startContentOffset;
@property(nonatomic) _Bool reseted; // @synthesize reseted=_reseted;
@property(nonatomic) _Bool whyPullMeShowState; // @synthesize whyPullMeShowState=_whyPullMeShowState;
@property(nonatomic) _Bool tapTicState; // @synthesize tapTicState=_tapTicState;
@property(nonatomic) double lastVisibleBackgroundOffsetY; // @synthesize lastVisibleBackgroundOffsetY=_lastVisibleBackgroundOffsetY;
@property(nonatomic) double lastStickingOffsetY; // @synthesize lastStickingOffsetY=_lastStickingOffsetY;
@property(nonatomic) double lastLoadingImageVisibleOffsetY; // @synthesize lastLoadingImageVisibleOffsetY=_lastLoadingImageVisibleOffsetY;
@property(nonatomic) double lastVisibleOffsetY; // @synthesize lastVisibleOffsetY=_lastVisibleOffsetY;
@property(nonatomic) _Bool visibleReachEnd; // @synthesize visibleReachEnd=_visibleReachEnd;
@property(retain, nonatomic) UIImage *animateGif; // @synthesize animateGif=_animateGif;
@property(retain, nonatomic) WAMainFrameTaskBarLogic *taskBarLogic; // @synthesize taskBarLogic=_taskBarLogic;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGestureOnStarCollectionView; // @synthesize longPressGestureOnStarCollectionView=_longPressGestureOnStarCollectionView;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGestureOnTaskCollectionView; // @synthesize longPressGestureOnTaskCollectionView=_longPressGestureOnTaskCollectionView;
@property(retain, nonatomic) UILabel *whyPullMeTipsLabel; // @synthesize whyPullMeTipsLabel=_whyPullMeTipsLabel;
@property(retain, nonatomic) WAMainFrameTaskBarDotLoadingView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(retain, nonatomic) UILabel *emptyTips; // @synthesize emptyTips=_emptyTips;
@property(retain, nonatomic) UIImageView *emptyLogo; // @synthesize emptyLogo=_emptyLogo;
@property(retain, nonatomic) UIView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) WAMainFrameTaskBarCollectionViewLayout *starCollectionViewLayout; // @synthesize starCollectionViewLayout=_starCollectionViewLayout;
@property(retain, nonatomic) UICollectionView *starCollectionView; // @synthesize starCollectionView=_starCollectionView;
@property(retain, nonatomic) UIButton *starTitleButton; // @synthesize starTitleButton=_starTitleButton;
@property(retain, nonatomic) UIImageView *starTitleArrow; // @synthesize starTitleArrow=_starTitleArrow;
@property(retain, nonatomic) UILabel *starTitleLabel; // @synthesize starTitleLabel=_starTitleLabel;
@property(retain, nonatomic) UIView *gapMarginView; // @synthesize gapMarginView=_gapMarginView;
@property(retain, nonatomic) WAMainFrameTaskBarCollectionViewLayout *taskCollectionViewLayout; // @synthesize taskCollectionViewLayout=_taskCollectionViewLayout;
@property(retain, nonatomic) UICollectionView *taskCollectionView; // @synthesize taskCollectionView=_taskCollectionView;
@property(retain, nonatomic) UIButton *taskTitleButton; // @synthesize taskTitleButton=_taskTitleButton;
@property(retain, nonatomic) UIImageView *taskTitleArrow; // @synthesize taskTitleArrow=_taskTitleArrow;
@property(retain, nonatomic) UILabel *taskTitleLabel; // @synthesize taskTitleLabel=_taskTitleLabel;
@property(retain, nonatomic) UIView *topMarginView; // @synthesize topMarginView=_topMarginView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) _Bool draggingShowState; // @synthesize draggingShowState=_draggingShowState;
@property(retain, nonatomic) UIView *fakeNavigationBackground; // @synthesize fakeNavigationBackground=_fakeNavigationBackground;
@property(retain, nonatomic) UIView *fakeNavigationBottomBackground; // @synthesize fakeNavigationBottomBackground=_fakeNavigationBottomBackground;
@property(nonatomic) _Bool containerVCDisappearing; // @synthesize containerVCDisappearing=_containerVCDisappearing;
@property(nonatomic) __weak MMUIViewController *containerVC; // @synthesize containerVC=_containerVC;
@property(nonatomic) _Bool isNeedMoreButton; // @synthesize isNeedMoreButton=_isNeedMoreButton;
@property(nonatomic) __weak id <WAMainFrameTaskBarViewDelegate> taskBarViewDelegate; // @synthesize taskBarViewDelegate=_taskBarViewDelegate;
- (void).cxx_destruct;
- (struct CGSize)externalSizeForLayout:(id)arg1;
- (struct CGSize)pageSizeForLayout:(id)arg1;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct CGSize)itemSizeForStar;
- (struct CGSize)itemSizeForTask;
- (double)pageWidthForStar;
- (double)pageWidthForTask;
- (void)scrollView:(id)arg1 scrollToContentOffset:(struct CGPoint)arg2;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)voiceTic;
- (void)taptic;
- (id)taskItemAtRowIndex:(long long)arg1;
- (void)showTipsViewController:(id)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (_Bool)canBecomeFirstResponder;
- (void)scrollToItemIndex:(long long)arg1 forCollectionView:(id)arg2;
- (void)onStarTitleButton:(id)arg1;
- (void)onTaskTitleButton:(id)arg1;
- (void)onDeleteStar:(id)arg1;
- (void)onDeleteTask:(id)arg1;
- (void)onAddToStar:(id)arg1;
- (void)onMoveToTop:(id)arg1;
- (void)onLongPressStarCollectionView:(id)arg1;
- (void)onLongPressTaskColletionView:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)layoutWhyPullMeTips;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (double)calScreenWidth;
- (double)calItemGap;
- (double)calMarginViewHeight;
- (double)calBottomMarginHeight;
- (double)calTitleTopMarginHeight;
- (double)calStarNodeHeight;
- (double)calStarCollectionViewHeight;
- (double)calTaskNodeHeight;
- (double)calTaskCollectionViewHeight;
- (void)layoutArrow;
- (void)layoutEmptyView;
- (void)layoutContentView;
- (void)layoutBackgroundView;
- (void)updateEmptyViewState;
- (void)reloadCollectionViews;
- (void)reloadData;
- (void)initEmptyView;
- (void)initStarCollectionView;
- (void)initGapMarginView;
- (void)initTaskCollectionView;
- (void)initTopMarginView;
- (void)initWhyPullMeTips;
- (void)initArrow;
- (void)initContentView;
- (void)initBackgroundView;
- (void)initView;
- (_Bool)shouldShowStarNodes;
- (_Bool)shouldShowTaskNodes;
- (void)checkViewNodes;
- (void)layoutSubviews;
- (void)unHighlightVisibleCell;
- (void)didRotate:(id)arg1;
- (void)onMenuControllerWillHide:(id)arg1;
- (void)reset;
- (void)unreset;
- (void)animateToHideWhyPullMeTips;
- (void)animateToShowWhyPullMeTips;
- (void)animateToHide;
- (void)animateToShowBackground;
- (void)animateToShow;
- (void)markAnimating;
- (void)updateFloatingProgress:(double)arg1 borderOffset:(double)arg2;
- (void)updateVisibleOffsetReachEnd;
- (void)updateBackgroundAlphaProgress:(double)arg1;
- (void)updateAlphaProgress:(double)arg1;
- (void)updateFilteredBackgroundVisibleOffset:(double)arg1 borderOffset:(double)arg2;
- (void)updateBackgroundVisibleOffset:(double)arg1 borderOffset:(double)arg2;
- (void)updateFilteredVisibleOffset:(double)arg1 startOffset:(double)arg2 borderOffset:(double)arg3;
- (void)updateVisibleOffset:(double)arg1 startOffset:(double)arg2 borderOffset:(double)arg3;
- (void)updateFilteredVisiableOffset:(double)arg1 borderOffset:(double)arg2;
- (void)updateVisiableOffset:(double)arg1 borderOffset:(double)arg2;
- (void)updateFilteredStickingOffset:(double)arg1;
- (void)updateStickingOffset:(double)arg1;
- (void)moveToLeftMostStarItem;
- (void)moveToLeftMostTaskItem;
- (id)getBackgroundViewColor;
- (double)calTaskBarHeight;
- (void)dealloc;
- (id)initWithMainFrameTaskBarLogic:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

