//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "WAAppItemManagerExtension.h"
#import "WAMainFrameTaskBarViewDelegate.h"
#import "WAMainListStarLogicDelegate.h"
#import "WASearchControllerDelegate.h"

@class MMUIViewController, NSMutableArray, NSMutableDictionary, NSString, WAMainListStarLogic, WAPackageSweeperLogic, WAReportMainFrameTaskBarActionItem, WASearchController;

@interface WAMainFrameTaskBarLogic : MMObject <WAAppItemManagerExtension, WAMainFrameTaskBarViewDelegate, WAMainListStarLogicDelegate, WASearchControllerDelegate>
{
    _Bool _isDraggingVisible;
    _Bool _isPullingWhyDragMe;
    unsigned int _openTime;
    id <WAMainFrameTaskBarLogicDelegate> _delegate;
    NSMutableArray *_arrTaskItem;
    MMUIViewController *_containerVC;
    WAMainListStarLogic *_starLogic;
    WASearchController *_searchController;
    WAReportMainFrameTaskBarActionItem *_actionItem;
    WAPackageSweeperLogic *_sweeperLogic;
    NSMutableDictionary *_conflicts;
}

@property(retain, nonatomic) NSMutableDictionary *conflicts; // @synthesize conflicts=_conflicts;
@property(retain, nonatomic) WAPackageSweeperLogic *sweeperLogic; // @synthesize sweeperLogic=_sweeperLogic;
@property(retain, nonatomic) WAReportMainFrameTaskBarActionItem *actionItem; // @synthesize actionItem=_actionItem;
@property(nonatomic) unsigned int openTime; // @synthesize openTime=_openTime;
@property(nonatomic) _Bool isPullingWhyDragMe; // @synthesize isPullingWhyDragMe=_isPullingWhyDragMe;
@property(nonatomic) _Bool isDraggingVisible; // @synthesize isDraggingVisible=_isDraggingVisible;
@property(retain, nonatomic) WASearchController *searchController; // @synthesize searchController=_searchController;
@property(retain, nonatomic) WAMainListStarLogic *starLogic; // @synthesize starLogic=_starLogic;
@property(nonatomic) __weak MMUIViewController *containerVC; // @synthesize containerVC=_containerVC;
@property(retain, nonatomic) NSMutableArray *arrTaskItem; // @synthesize arrTaskItem=_arrTaskItem;
@property(nonatomic) __weak id <WAMainFrameTaskBarLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onWeAppItemBatchMoved:(id)arg1;
- (void)onWeAppItemDeleted:(id)arg1;
- (void)onWeAppItemOpened:(id)arg1;
- (void)onWeAppItemsInfoUpdatedWithAPageItem:(id)arg1 localLastUpdateTime:(unsigned int)arg2 remoteLastUpdateTime:(unsigned int)arg3 hasMore:(_Bool)arg4 scene:(unsigned int)arg5;
- (void)starDataDidUpdated;
- (void)appItemDidUnStaredSuccess:(id)arg1;
- (void)appItemDidStaredSuccess:(id)arg1;
- (void)willEndSearch;
- (double)getFullScreenHeight;
- (void)whyDragMeTick;
- (void)visibleTick;
- (void)endPullWhyDragMe;
- (void)startPullWhyDragMe;
- (void)endDragToVisible;
- (void)startDragToVisible;
- (void)mergeConflictModel:(id)arg1 toConflictAction:(id)arg2;
- (void)checkConflictInList:(id)arg1 listType:(unsigned long long)arg2;
- (void)reportConflictActionIfNeeded;
- (void)reportVisitAction;
- (void)taskBarDidHideWithScene:(unsigned long long)arg1;
- (void)taskBarDidShow;
- (void)closeRunningTaskIfHaveByUsername:(id)arg1 debugType:(unsigned int)arg2;
- (void)didAddToStarItemWithUsername:(id)arg1 debugType:(unsigned int)arg2;
- (void)didMoveStarItemToTopWithUsername:(id)arg1 debugType:(unsigned int)arg2;
- (void)didMoveStarItemWithUsername:(id)arg1 debugType:(unsigned int)arg2;
- (void)didDeleteStarItemWithUsername:(id)arg1 debugType:(unsigned int)arg2;
- (void)didDeleteTaskItemWithUsername:(id)arg1 debugType:(unsigned int)arg2;
- (unsigned long long)removeTaskBarItemByUsername:(id)arg1 debugType:(unsigned int)arg2;
- (void)taskBarView:(id)arg1 didRotateToInterfaceOrientation:(long long)arg2;
- (void)taskBarView:(id)arg1 notifyOnTranslationYChanged:(double)arg2;
- (void)taskBarViewDidTapOnSearchButton:(id)arg1;
- (void)taskBarViewDidTapOnFoldButton:(id)arg1;
- (void)taskBarView:(id)arg1 heightDidChangeTo:(double)arg2;
- (void)taskBarView:(id)arg1 onStarNodeShowStatusDidChangedTo:(_Bool)arg2;
- (void)taskBarViewStarDidEndDragging:(id)arg1;
- (void)taskBarViewTaskDidEndDragging:(id)arg1;
- (void)taskBarViewDidSelectStarMore:(id)arg1;
- (void)taskBarViewDidSelectTaskMore:(id)arg1;
- (void)taskBarViewDidSelectMore:(id)arg1;
- (void)taskBarView:(id)arg1 didSelectStarItem:(id)arg2 onPosition:(unsigned long long)arg3;
- (void)taskBarView:(id)arg1 didSelectTaskItem:(id)arg2 onPosition:(unsigned long long)arg3;
- (unsigned int)getTaskMaxCount;
- (_Bool)isSupportWeapp;
- (_Bool)isShouldShowTaskBarView;
- (id)taskItemAtRowIndex:(long long)arg1;
- (void)loadTaskItemListWithCount:(unsigned int)arg1;
- (_Bool)updateContactsFromScene:(unsigned long long)arg1;
- (void)reloadStarItems;
- (void)reloadTaskItems;
- (void)dealloc;
- (void)preCheckAndUpdateInvalidContactsInScene:(unsigned long long)arg1;
- (void)initData;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

