//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class GetProfileInfoResponse_WxaLikeWording, MMUIButton, MMUILabel, NSMutableArray, NSString;

@interface WAProfileLikeListCell : UITableViewCell
{
    NSMutableArray *_likeList;
    unsigned int _totalLikeCnt;
    GetProfileInfoResponse_WxaLikeWording *_wxaLikeWording;
    NSString *_weAppName;
    _Bool _bMyselfLiked;
    MMUILabel *_titleLabel;
    MMUIButton *_likeButton;
    double _lastWidth;
    id <WAProfileLikeListCellDelegate> _delegate;
}

+ (double)cellHeight;
@property(nonatomic) __weak id <WAProfileLikeListCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onLikeListMoreClick;
- (void)onLikeButtonClick:(id)arg1;
- (long long)getMyselfLikeIndex;
- (void)layoutSubviews;
- (void)updateLikeListInfo:(id)arg1 FriendLikeList:(id)arg2;
- (void)setupNormalLikeListSubviews;
- (void)setupEmptyLikeListSubviews;
- (void)addRealLikeActionButton;
- (void)setupSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

