//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBMessageObserverDelegate.h"

@class NSMutableArray, NSMutableSet, NSString;

@interface WAWeAppBindBrandListPageLogic : MMObject <PBMessageObserverDelegate>
{
    _Bool _hasNoMore;
    unsigned int _currentPageNum;
    NSMutableArray *_bindItems;
    id <WAWeAppBindBrandListPageLogicDelegate> _delegate;
    NSString *_appid;
    NSString *_previousPageBuffer;
    NSMutableSet *_usernameSet;
}

@property(retain, nonatomic) NSMutableSet *usernameSet; // @synthesize usernameSet=_usernameSet;
@property(copy, nonatomic) NSString *previousPageBuffer; // @synthesize previousPageBuffer=_previousPageBuffer;
@property(copy, nonatomic) NSString *appid; // @synthesize appid=_appid;
@property(readonly, nonatomic) unsigned int currentPageNum; // @synthesize currentPageNum=_currentPageNum;
@property(readonly, nonatomic) _Bool hasNoMore; // @synthesize hasNoMore=_hasNoMore;
@property(nonatomic) __weak id <WAWeAppBindBrandListPageLogicDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSMutableArray *bindItems; // @synthesize bindItems=_bindItems;
- (void).cxx_destruct;
- (id)getBindItemsFromBindBizInfo:(id)arg1;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)fetchNextPageItems;
- (id)trimBrandList:(id)arg1;
- (void)recordUsernameInBrandList:(id)arg1;
- (void)dealloc;
- (id)initWithFirstPageBrandList:(id)arg1 appid:(id)arg2;

@end

