//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCBlockMonitorConfiguration;

@interface WCBlockMonitorConfigHandler : NSObject
{
    int m_cpuCount;
    WCBlockMonitorConfiguration *m_currentConfiguration;
}

+ (int)getDeviceCPUCount;
- (void).cxx_destruct;
- (_Bool)getShouldPrintCPUUsage;
- (unsigned long long)getFrameDropLimit;
- (int)getMainThreadCount;
- (unsigned int)getPerStackInterval;
- (unsigned int)getCheckPeriodTime;
- (_Bool)getMainThreadHandle;
- (float)getCPUUsagePercent;
- (unsigned int)getRunloopTimeOut;
- (_Bool)getIsMonitor;
- (void)setConfiguration:(id)arg1;
- (id)init;

@end

