//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIFont.h"

@interface WCFont : UIFont
{
}

+ (id)wcfontWithSize:(int)arg1;
+ (id)Caption;
+ (id)FootNote;
+ (id)Desc;
+ (id)Body;
+ (id)Heading;
+ (id)Title;

@end

