//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMMultiMenuTableViewCell.h"

@class CardHomePageElement, MMUILabel, UIButton, UIImageView, UIView, WCPayWebImageView;

@interface WCMktMerchatUnderItemCell : MMMultiMenuTableViewCell
{
    CardHomePageElement *_elemData;
    WCPayWebImageView *_merchatLogoImgView;
    MMUILabel *_merchatNameLabel;
    MMUILabel *_tradeRelationLabel;
    UIButton *_mchActTagBtn;
    UIImageView *_arrowImgView;
    UIView *_sepBarView;
    UIView *_maskView;
}

@property(retain, nonatomic) UIView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) UIView *sepBarView; // @synthesize sepBarView=_sepBarView;
@property(retain, nonatomic) UIImageView *arrowImgView; // @synthesize arrowImgView=_arrowImgView;
@property(retain, nonatomic) UIButton *mchActTagBtn; // @synthesize mchActTagBtn=_mchActTagBtn;
@property(retain, nonatomic) MMUILabel *tradeRelationLabel; // @synthesize tradeRelationLabel=_tradeRelationLabel;
@property(retain, nonatomic) MMUILabel *merchatNameLabel; // @synthesize merchatNameLabel=_merchatNameLabel;
@property(retain, nonatomic) WCPayWebImageView *merchatLogoImgView; // @synthesize merchatLogoImgView=_merchatLogoImgView;
@property(retain, nonatomic) CardHomePageElement *elemData; // @synthesize elemData=_elemData;
- (void).cxx_destruct;
- (void)updateTagButtonWithElemMchLabelData:(id)arg1 tagBtn:(id)arg2;
- (void)updateContentWithData:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

