//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "ILinkEventExt.h"
#import "WCPayAddressRemarkViewDelegate.h"
#import "WCPayGetTransferWordingCgiDelegate.h"
#import "WCPayNoticeBannerDelegate.h"

@class GetTransferWordingResponse, NSString, WCPayGetTransferWordingCgi, WCPayNoticeBanner;

@interface WCPayTransferMoneyStatusViewController : WCPayBaseViewController <WCPayAddressRemarkViewDelegate, WCPayGetTransferWordingCgiDelegate, WCPayNoticeBannerDelegate, ILinkEventExt>
{
    id <WCPayTransferMoneyStatusViewControllerDelegate> m_delegate;
    _Bool _m_expendAddress;
    _Bool _m_shouldRefreshDataOnAppear;
    WCPayGetTransferWordingCgi *_wordingCgi;
    GetTransferWordingResponse *_wordingResponse;
    WCPayNoticeBanner *_noticeBanner;
}

@property _Bool m_shouldRefreshDataOnAppear; // @synthesize m_shouldRefreshDataOnAppear=_m_shouldRefreshDataOnAppear;
@property _Bool m_expendAddress; // @synthesize m_expendAddress=_m_expendAddress;
@property(retain, nonatomic) WCPayNoticeBanner *noticeBanner; // @synthesize noticeBanner=_noticeBanner;
@property(retain, nonatomic) GetTransferWordingResponse *wordingResponse; // @synthesize wordingResponse=_wordingResponse;
@property(retain, nonatomic) WCPayGetTransferWordingCgi *wordingCgi; // @synthesize wordingCgi=_wordingCgi;
- (void).cxx_destruct;
- (void)reportAction:(unsigned long long)arg1;
- (void)onWCPayAddressRemarkViewCopy;
- (void)onWCPayAddressRemarkViewExpend;
- (void)banner:(id)arg1 clickWithUrl:(id)arg2;
- (id)getSubTitleWordingInLocal:(_Bool)arg1;
- (id)getMainTitleWordingInLocal:(_Bool)arg1 receiverContact:(id)arg2;
- (void)wcpayGetTransferWordingCgi:(id)arg1 didGetResponse:(id)arg2;
- (void)onOpenQA;
- (void)requestWording;
- (void)OnRealnameSucceed;
- (void)OnConfirmTransferMoneyBtnDone;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)refreshViewWithData:(id)arg1;
- (void)onClickJumpInfo:(id)arg1;
- (void)onClickAddressJumpInfo;
- (void)onClickTextInfo;
- (_Bool)isNotSentFromMeAndWaitingForReceive;
- (void)updateFooterButton:(id)arg1;
- (void)updateAddressInfo:(id)arg1;
- (void)reloadTableView;
- (id)navigationBarBackgroundColor;
- (void)initNavigationBar;
- (void)OnHistoryOrderDetailBack;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

