//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class NSHashTable, NSIndexPath, NSString, UICollectionView, UICollectionViewFlowLayout, WCStoryDataUnit, WCStoryPreviewPageView;

@interface WCStoryPreivewPageCollectionController : MMObject <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
{
    UICollectionViewFlowLayout *m_collectionLayout;
    WCStoryPreviewPageView *m_playingPageView;
    double m_startContentOffsetX;
    double m_willEndContentOffsetX;
    NSHashTable *m_pageViewsToStop;
    _Bool _needFixContentOffset;
    _Bool _resetToFirstPageWhenUpdateData;
    _Bool _isAllMuted;
    _Bool _isPlayingVideo;
    _Bool _enableDragToClose;
    _Bool _canDeleteMyOwnStory;
    UICollectionView *m_collectionView;
    NSIndexPath *m_currentIndexPath;
    id <WCStoryPreivewPageCollectionControllerDelegate> _delegate;
    id <WCStoryPreviewPageViewDelegate> _pageViewDelegate;
    id <MMUIViewControllerDelegate> _vcDelegate;
    WCStoryDataUnit *_dataUnit;
    struct CGSize _screenSize;
}

@property(nonatomic) _Bool canDeleteMyOwnStory; // @synthesize canDeleteMyOwnStory=_canDeleteMyOwnStory;
@property(nonatomic) _Bool enableDragToClose; // @synthesize enableDragToClose=_enableDragToClose;
@property(nonatomic) _Bool isPlayingVideo; // @synthesize isPlayingVideo=_isPlayingVideo;
@property(nonatomic) _Bool isAllMuted; // @synthesize isAllMuted=_isAllMuted;
@property(nonatomic) _Bool resetToFirstPageWhenUpdateData; // @synthesize resetToFirstPageWhenUpdateData=_resetToFirstPageWhenUpdateData;
@property(nonatomic) _Bool needFixContentOffset; // @synthesize needFixContentOffset=_needFixContentOffset;
@property(retain, nonatomic) WCStoryDataUnit *dataUnit; // @synthesize dataUnit=_dataUnit;
@property(nonatomic) struct CGSize screenSize; // @synthesize screenSize=_screenSize;
@property(nonatomic) __weak id <MMUIViewControllerDelegate> vcDelegate; // @synthesize vcDelegate=_vcDelegate;
@property(nonatomic) __weak id <WCStoryPreviewPageViewDelegate> pageViewDelegate; // @synthesize pageViewDelegate=_pageViewDelegate;
@property(nonatomic) __weak id <WCStoryPreivewPageCollectionControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSIndexPath *currentIndexPath; // @synthesize currentIndexPath=m_currentIndexPath;
@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=m_collectionView;
- (void).cxx_destruct;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)clearAllPageView;
- (void)addSafeStopPageView:(id)arg1;
- (void)changeToPlayingPageView:(id)arg1;
- (void)tilePages;
- (void)fixContentOffset;
- (void)reloadCollectionView;
- (void)scrollToIndexPath:(id)arg1 animated:(_Bool)arg2;
- (void)stopAllPlayer;
- (void)resumePlayer;
- (id)previewPageViewWithStoryTid:(id)arg1;
@property(readonly, nonatomic) WCStoryPreviewPageView *currentPageView;
- (void)updateCollectionViewFrame;
- (void)configCollectionView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

