//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCStoryBubbleListView;

@protocol WCStoryBubbleListViewDelegate <NSObject>

@optional
- (void)onBubbleListViewHasPlayFirstReadedItem:(WCStoryBubbleListView *)arg1;
- (void)onBubbleListViewHasPlayOneTime:(WCStoryBubbleListView *)arg1;
@end

