//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, WCStoryComment, WCStoryDataItem, WCStoryZonePageIndexObj;

@protocol WCStoryFacadeExt <NSObject>

@optional
- (void)onCameraRedDotCleaned;
- (void)onDeleteStoryWithStory:(WCStoryDataItem *)arg1 PageIndexObj:(WCStoryZonePageIndexObj *)arg2;
- (void)onCleanUnReadStorys:(NSArray *)arg1;
- (void)onUserStoryPageFromZerotoOne:(NSString *)arg1;
- (void)onStoryUnreadCommentCountUpdate;
- (void)onStoryUploadSuccessWithDataItem:(WCStoryDataItem *)arg1;
- (void)onStoryUploadFailWithDataItem:(WCStoryDataItem *)arg1;
- (void)onStoryUploadRetry:(WCStoryDataItem *)arg1;
- (void)onStoryCommentDeleteSuccessWithStoryId:(NSString *)arg1 CommentId:(NSString *)arg2;
- (void)onStoryDeleteSuccessWithDataTid:(NSString *)arg1;
- (void)onCommentSuccess:(WCStoryComment *)arg1;
- (void)onCommentFail:(WCStoryComment *)arg1;
- (void)onDataItemAllCommentMakeRead:(WCStoryDataItem *)arg1;
- (void)onGetStoryUnReadComment:(WCStoryDataItem *)arg1;
@end

