//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "WCStoryPreivewPageCollectionControllerDelegate.h"
#import "WCStoryPreviewPageViewDelegate.h"

@class NSString, WCStoryDataUnit, WCStoryPageControl, WCStoryPreivewPageCollectionController;

@interface WCStoryMultiContactPreviewCell : UICollectionViewCell <WCStoryPreivewPageCollectionControllerDelegate, WCStoryPreviewPageViewDelegate>
{
    id <WCStoryMultiContactPreviewCellDelegate> _delegate;
    WCStoryDataUnit *_dataUnit;
    WCStoryPreivewPageCollectionController *_controller;
    WCStoryPageControl *_pageControl;
}

@property(retain, nonatomic) WCStoryPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) WCStoryPreivewPageCollectionController *controller; // @synthesize controller=_controller;
@property(retain, nonatomic) WCStoryDataUnit *dataUnit; // @synthesize dataUnit=_dataUnit;
@property(nonatomic) __weak id <WCStoryMultiContactPreviewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onLongPressToDeletePageView:(id)arg1;
- (void)onStoryPageCollectionControllerChangePage:(id)arg1 pageView:(id)arg2 lastIndexPath:(id)arg3;
- (void)reloadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

