//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@interface WCSUITextFieldCheck : MMObject
{
    struct shared_ptr<__WCSBCP> check;
    _Bool _tracking;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onEditChange:(id)arg1;
- (void)onEndEdit:(id)arg1;
- (void)onBeginEdit:(id)arg1;
- (id)getData;
- (void)pause;
- (void)stop;
- (void)start;
- (void)printResult;
- (void)dealloc;
- (id)init;

@end

