//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMMLanguageMgrExt.h"
#import "MMKernelExt.h"
#import "WCUpdateResourceExt.h"

@class NSBundle, NSObject<OS_dispatch_queue>, NSString, WCUpdateInfo;

@interface WCUpdateMgr : NSObject <WCUpdateResourceExt, MMKernelExt, IMMLanguageMgrExt>
{
    NSBundle *_resourceBundle;
    NSBundle *_languageBundle;
    WCUpdateInfo *_patchInfo;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)getInstance;
- (void).cxx_destruct;
- (void)cleanOldOne;
- (_Bool)unzipBundleUpdates;
- (_Bool)unzipDownloadUpdates:(id)arg1;
- (_Bool)_loadBundleWithoutCheck:(id)arg1;
- (void)exitOnEnteringBackground;
- (void)setNewClientVersionInUserDefault:(unsigned int)arg1;
- (void)clearNewClientVersionInUserDefault;
- (unsigned int)newClientVersion;
- (_Bool)runPatch;
- (id)getPatchInfo:(id)arg1;
- (void)onLanguageChange;
- (void)onAuthOKWithPlistVesionChangeFrom:(unsigned int)arg1 to:(unsigned int)arg2;
- (void)onPatchResDeleteFinish;
- (void)onPatchResUpdateFinish:(unsigned long long)arg1;
- (void)dealloc;
- (void)forceUpdate:(unsigned int)arg1;
- (void)registerExtension;
- (_Bool)loadBundle:(id)arg1 withIDKey:(const struct WCVMBundleLoadIDKey *)arg2;
- (_Bool)loadBundleWithoutIDKeyReport:(id)arg1;
- (_Bool)loadPluginInBundle:(id)arg1 withIDKey:(const struct WCVMBundleLoadIDKey *)arg2;
- (_Bool)loadPluginInBundle:(id)arg1;
- (void)loadAndExecute;
- (id)init;
- (id)getPluginPathInBundle:(id)arg1;
- (id)getPluginPathInUpdate:(id)arg1;
- (id)getStringForCurLanguage:(id)arg1 defaultTo:(id)arg2;
- (id)getBundleResource:(id)arg1 ext:(id)arg2;
- (id)imageNamed:(id)arg1;
- (_Bool)loadResource;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

