//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WSVideoModel;

@protocol WSVideoFlowDataDelegate <NSObject>

@optional
- (void)onTryResumeExpiredPlayer;
- (_Bool)onCheckCurrentVideoHandlingExpired;
- (NSString *)onGetInteractiveVid;
- (void)onSuccessInsertVideo:(WSVideoModel *)arg1 fromVid:(NSString *)arg2;
- (void)onFailInsertVideo:(WSVideoModel *)arg1 reason:(int)arg2;
- (unsigned long long)onGetLastVisibleCellIndex;
- (void)onVoteCgiReturn:(_Bool)arg1 opType:(int)arg2 docId:(NSString *)arg3;
- (void)onDefaultVideoUpdated;
- (void)onUpdatePrefetchFlag:(_Bool)arg1;
- (void)onReturnFromWebRecommendVideo:(int)arg1;
@end

