//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface WxaHBInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *appid; // @dynamic appid;
@property(nonatomic) unsigned long long createTime; // @dynamic createTime;
@property(retain, nonatomic) NSString *extmess; // @dynamic extmess;
@property(retain, nonatomic) NSString *hbKey; // @dynamic hbKey;
@property(nonatomic) unsigned int hbScope; // @dynamic hbScope;
@property(nonatomic) int hbType; // @dynamic hbType;
@property(retain, nonatomic) NSString *reqkey; // @dynamic reqkey;
@property(retain, nonatomic) NSString *sendid; // @dynamic sendid;
@property(nonatomic) unsigned int status; // @dynamic status;
@property(nonatomic) unsigned long long updateTime; // @dynamic updateTime;
@property(nonatomic) unsigned int useruin; // @dynamic useruin;

@end

