//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "CNetworkStatusExt.h"
#import "IChatMigrationServerExt.h"
#import "MMLoadSessionExt.h"

@class NSString, UIActivityIndicatorView, UIImage, UIImageView, UILabel;

@interface WXGMigrationServerViewController : MMUIViewController <IChatMigrationServerExt, CNetworkStatusExt, MMLoadSessionExt>
{
    UIImageView *m_qrCodeImageView;
    UILabel *m_qrCodeTipLabel;
    UIActivityIndicatorView *m_qrCodeLoadingView;
    UIImage *m_qrcodeImage;
    int m_retryGetQRCodeTimes;
    _Bool _isMigrationAllAndNeedWaitLoad;
    _Bool _isSessionDataLoadFinish;
}

@property(nonatomic) _Bool isSessionDataLoadFinish; // @synthesize isSessionDataLoadFinish=_isSessionDataLoadFinish;
@property(nonatomic) _Bool isMigrationAllAndNeedWaitLoad; // @synthesize isMigrationAllAndNeedWaitLoad=_isMigrationAllAndNeedWaitLoad;
- (void).cxx_destruct;
- (void)ReachabilityChange:(unsigned int)arg1;
- (void)onMigrationServerAlertCode:(unsigned long long)arg1;
- (void)onMigrationServerNotifyCode:(unsigned long long)arg1;
- (void)onGetQRCodeImg:(id)arg1;
- (void)onLoadDataFinished;
- (void)loadSessionArrayFinishAndShowQRCode;
- (void)p_setQRCodeTipLabelWithText:(id)arg1;
- (void)p_makeQRCodeImageFailureFinishState;
- (void)p_makeQRCodeImageFinishState:(id)arg1 withText:(id)arg2;
- (void)p_makeQRCodeLoadingState;
- (void)onPressLeftNavigationButton;
- (void)p_popNavigationController;
- (void)popToSettingViewController;
- (void)dealloc;
- (void)registerLoadSessionExtension;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

