# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'MonkeyDevDemoDylib' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FLEX'
  # Pods for MonkeyDevDemoDylib

end
