//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "WCTTableCoding.h"

@class NSString, PublicWifiCache, PublicWifiPageInfo;

@interface APBase : MMObject <WCTTableCoding>
{
    NSString *ssid;
    NSString *mac;
    unsigned int opCode;
    PublicWifiCache *cache;
    unsigned int scene;
    NSString *qrCode;
    NSString *mpUrl;
    NSString *mid;
    NSString *checkUrl;
    NSString *sessionKey;
    NSString *password;
    unsigned int retcode;
    NSString *errMsg;
    int _state;
    int _actionCode;
    unsigned int _protocolType;
    NSString *_bannerText;
    NSString *_showUrl;
    double _expiredTime;
    NSString *_retMsg;
    PublicWifiPageInfo *_pageInfo;
}

+ (void)__wcdb_APBase_primary_14:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)retMsg;
+ (void)__wcdb_APBase_synthesize_13:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)retcode;
+ (void)__wcdb_APBase_synthesize_12:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)protocolType;
+ (void)__wcdb_APBase_synthesize_11:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)checkUrl;
+ (void)__wcdb_APBase_synthesize_10:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)mid;
+ (void)__wcdb_APBase_synthesize_9:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)mpUrl;
+ (void)__wcdb_APBase_synthesize_8:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)qrCode;
+ (void)__wcdb_APBase_synthesize_7:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)expiredTime;
+ (void)__wcdb_APBase_synthesize_6:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)showUrl;
+ (void)__wcdb_APBase_synthesize_5:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)bannerText;
+ (void)__wcdb_APBase_synthesize_4:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)actionCode;
+ (void)__wcdb_APBase_synthesize_3:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)opCode;
+ (void)__wcdb_APBase_synthesize_2:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)mac;
+ (void)__wcdb_APBase_synthesize_1:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)ssid;
+ (void)__wcdb_APBase_synthesize_0:(struct WCTBinding *)arg1;
+ (CDUnknownBlockType)columnNamed;
+ (const struct All *)allResults;
+ (const struct WCTPropertyList *)allProperties;
+ (const struct WCTBinding *)objectRelationalMapping;
@property(retain, nonatomic) PublicWifiPageInfo *pageInfo; // @synthesize pageInfo=_pageInfo;
@property(copy, nonatomic) NSString *retMsg; // @synthesize retMsg=_retMsg;
@property(nonatomic) unsigned int protocolType; // @synthesize protocolType=_protocolType;
@property(nonatomic) double expiredTime; // @synthesize expiredTime=_expiredTime;
@property(copy, nonatomic) NSString *showUrl; // @synthesize showUrl=_showUrl;
@property(copy, nonatomic) NSString *bannerText; // @synthesize bannerText=_bannerText;
@property(nonatomic) int actionCode; // @synthesize actionCode=_actionCode;
@property(nonatomic) int state; // @synthesize state=_state;
@property(copy, nonatomic) NSString *checkUrl; // @synthesize checkUrl;
@property(copy, nonatomic) NSString *mid; // @synthesize mid;
@property(nonatomic) unsigned int opCode; // @synthesize opCode;
@property(copy, nonatomic) NSString *mpUrl; // @synthesize mpUrl;
@property(nonatomic) unsigned int retcode; // @synthesize retcode;
@property(copy, nonatomic) NSString *qrCode; // @synthesize qrCode;
@property(retain, nonatomic) NSString *mac; // @synthesize mac;
@property(retain, nonatomic) NSString *ssid; // @synthesize ssid;
@property(copy, nonatomic) NSString *password; // @synthesize password;
@property(copy, nonatomic) NSString *sessionKey; // @synthesize sessionKey;
@property(nonatomic) unsigned int scene; // @synthesize scene;
@property(nonatomic) __weak PublicWifiCache *cache; // @synthesize cache;
- (void).cxx_destruct;
- (void)handleHomeBarClicked:(id)arg1;
- (_Bool)canStartWithCurrSSID:(id)arg1;
- (void)cancel;
- (void)start;
- (id)description;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

