//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

@interface BrandTimelineSplitView : UIView
{
    UILabel *_tipsLabel;
    UIView *_leftLine;
    UIView *_rightLine;
}

@property(retain, nonatomic) UIView *rightLine; // @synthesize rightLine=_rightLine;
@property(retain, nonatomic) UIView *leftLine; // @synthesize leftLine=_leftLine;
@property(retain, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)internalInitWithWording:(id)arg1 font:(id)arg2;
- (id)initWithTipsWording:(id)arg1 font:(id)arg2;

@end

