//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@interface CAppBrandInfo : NSObject
{
    _Bool _hasAppInfo;
    _Bool _isUseModule;
    _Bool _webSocketSkipPortCheck;
    _Bool _canPreFetchData;
    _Bool _canPeriodFetchData;
    _Bool _TLSSkipHostnameCheck;
    unsigned int versionState;
    unsigned int maxPkgSize;
    unsigned int maxUploadConcurrent;
    unsigned int maxDownloadConcurrent;
    unsigned int maxLocalstorageSize;
    unsigned int maxOpendataLocalstorageSize;
    unsigned int maxBackgroundLifespan;
    unsigned int maxRequestConcurrent;
    unsigned int maxWebviewDepth;
    unsigned int runningFlag;
    unsigned int maxWorkerConcurrent;
    unsigned int _appServiceType;
    unsigned int _canNotStarWxaBeforeTime;
    unsigned int _appRole;
    unsigned int _wechatPluginApp;
    unsigned int _profileCommentForbid;
    unsigned int _originalFlag;
    unsigned int _maxWebsocketConnect;
    unsigned int _expendedMaxWebviewDepth;
    unsigned int _actualWebviewDepth;
    unsigned int _expiresAtList;
    unsigned int _maxFileStorageSize;
    unsigned int _maxOpendataFileStorageSize;
    unsigned int _backgroundNetworkInterruptedTimeout;
    unsigned int _lifeSpanBeforeSuspend;
    unsigned int _lifeSpanAfterSuspend;
    unsigned int _periodFetchDataHours;
    NSString *appid;
    unsigned long long appVersion;
    NSString *versionPkgMD5;
    NSString *loadingImgUrl;
    NSString *loadingImgProgressbarColor;
    NSString *_regitserBody;
    NSString *_shortNickName;
    NSString *_runningOpenForbbidenUrl;
    NSArray *_templateList;
    NSString *_fromBusinessUserName;
    NSArray *_versionList;
    NSArray *_requestDomain;
    NSArray *_wsRequestDomain;
    NSArray *_uploadDomain;
    NSArray *_downloadDomain;
    NSDictionary *_dicPluginInfo;
    NSString *_originalRedirectUrl;
    NSString *_deviceOrientation;
    NSArray *_arrModuleList;
    NSString *_entranceModule;
    NSDictionary *_dicClientJsExtInfo;
    NSArray *_categories;
    NSArray *_bizEntryInfo;
}

@property(retain, nonatomic) NSArray *bizEntryInfo; // @synthesize bizEntryInfo=_bizEntryInfo;
@property(retain, nonatomic) NSArray *categories; // @synthesize categories=_categories;
@property(nonatomic) _Bool TLSSkipHostnameCheck; // @synthesize TLSSkipHostnameCheck=_TLSSkipHostnameCheck;
@property(nonatomic) unsigned int periodFetchDataHours; // @synthesize periodFetchDataHours=_periodFetchDataHours;
@property(nonatomic) _Bool canPeriodFetchData; // @synthesize canPeriodFetchData=_canPeriodFetchData;
@property(nonatomic) _Bool canPreFetchData; // @synthesize canPreFetchData=_canPreFetchData;
@property(nonatomic) _Bool webSocketSkipPortCheck; // @synthesize webSocketSkipPortCheck=_webSocketSkipPortCheck;
@property(nonatomic) unsigned int lifeSpanAfterSuspend; // @synthesize lifeSpanAfterSuspend=_lifeSpanAfterSuspend;
@property(nonatomic) unsigned int lifeSpanBeforeSuspend; // @synthesize lifeSpanBeforeSuspend=_lifeSpanBeforeSuspend;
@property(nonatomic) unsigned int backgroundNetworkInterruptedTimeout; // @synthesize backgroundNetworkInterruptedTimeout=_backgroundNetworkInterruptedTimeout;
@property(nonatomic) unsigned int maxOpendataFileStorageSize; // @synthesize maxOpendataFileStorageSize=_maxOpendataFileStorageSize;
@property(nonatomic) unsigned int maxFileStorageSize; // @synthesize maxFileStorageSize=_maxFileStorageSize;
@property(nonatomic) unsigned int expiresAtList; // @synthesize expiresAtList=_expiresAtList;
@property(nonatomic) unsigned int actualWebviewDepth; // @synthesize actualWebviewDepth=_actualWebviewDepth;
@property(nonatomic) unsigned int expendedMaxWebviewDepth; // @synthesize expendedMaxWebviewDepth=_expendedMaxWebviewDepth;
@property(nonatomic) unsigned int maxWebsocketConnect; // @synthesize maxWebsocketConnect=_maxWebsocketConnect;
@property(retain, nonatomic) NSDictionary *dicClientJsExtInfo; // @synthesize dicClientJsExtInfo=_dicClientJsExtInfo;
@property(copy, nonatomic) NSString *entranceModule; // @synthesize entranceModule=_entranceModule;
@property(nonatomic) _Bool isUseModule; // @synthesize isUseModule=_isUseModule;
@property(retain, nonatomic) NSArray *arrModuleList; // @synthesize arrModuleList=_arrModuleList;
@property(copy, nonatomic) NSString *deviceOrientation; // @synthesize deviceOrientation=_deviceOrientation;
@property(copy, nonatomic) NSString *originalRedirectUrl; // @synthesize originalRedirectUrl=_originalRedirectUrl;
@property(nonatomic) unsigned int originalFlag; // @synthesize originalFlag=_originalFlag;
@property(retain, nonatomic) NSDictionary *dicPluginInfo; // @synthesize dicPluginInfo=_dicPluginInfo;
@property(retain, nonatomic) NSArray *downloadDomain; // @synthesize downloadDomain=_downloadDomain;
@property(retain, nonatomic) NSArray *uploadDomain; // @synthesize uploadDomain=_uploadDomain;
@property(retain, nonatomic) NSArray *wsRequestDomain; // @synthesize wsRequestDomain=_wsRequestDomain;
@property(retain, nonatomic) NSArray *requestDomain; // @synthesize requestDomain=_requestDomain;
@property(retain, nonatomic) NSArray *versionList; // @synthesize versionList=_versionList;
@property(copy, nonatomic) NSString *fromBusinessUserName; // @synthesize fromBusinessUserName=_fromBusinessUserName;
@property(nonatomic) unsigned int profileCommentForbid; // @synthesize profileCommentForbid=_profileCommentForbid;
@property(nonatomic) unsigned int wechatPluginApp; // @synthesize wechatPluginApp=_wechatPluginApp;
@property(retain, nonatomic) NSArray *templateList; // @synthesize templateList=_templateList;
@property(nonatomic) unsigned int appRole; // @synthesize appRole=_appRole;
@property(nonatomic) unsigned int canNotStarWxaBeforeTime; // @synthesize canNotStarWxaBeforeTime=_canNotStarWxaBeforeTime;
@property(copy, nonatomic) NSString *runningOpenForbbidenUrl; // @synthesize runningOpenForbbidenUrl=_runningOpenForbbidenUrl;
@property(nonatomic) unsigned int appServiceType; // @synthesize appServiceType=_appServiceType;
@property(copy, nonatomic) NSString *shortNickName; // @synthesize shortNickName=_shortNickName;
@property(nonatomic) _Bool hasAppInfo; // @synthesize hasAppInfo=_hasAppInfo;
@property(copy, nonatomic) NSString *regitserBody; // @synthesize regitserBody=_regitserBody;
@property(copy, nonatomic) NSString *loadingImgProgressbarColor; // @synthesize loadingImgProgressbarColor;
@property(copy, nonatomic) NSString *loadingImgUrl; // @synthesize loadingImgUrl;
@property(nonatomic) unsigned int maxWorkerConcurrent; // @synthesize maxWorkerConcurrent;
@property(nonatomic) unsigned int runningFlag; // @synthesize runningFlag;
@property(nonatomic) unsigned int maxWebviewDepth; // @synthesize maxWebviewDepth;
@property(nonatomic) unsigned int maxRequestConcurrent; // @synthesize maxRequestConcurrent;
@property(nonatomic) unsigned int maxBackgroundLifespan; // @synthesize maxBackgroundLifespan;
@property(nonatomic) unsigned int maxOpendataLocalstorageSize; // @synthesize maxOpendataLocalstorageSize;
@property(nonatomic) unsigned int maxLocalstorageSize; // @synthesize maxLocalstorageSize;
@property(nonatomic) unsigned int maxDownloadConcurrent; // @synthesize maxDownloadConcurrent;
@property(nonatomic) unsigned int maxUploadConcurrent; // @synthesize maxUploadConcurrent;
@property(nonatomic) unsigned int maxPkgSize; // @synthesize maxPkgSize;
@property(copy, nonatomic) NSString *versionPkgMD5; // @synthesize versionPkgMD5;
@property(nonatomic) unsigned long long appVersion; // @synthesize appVersion;
@property(nonatomic) unsigned int versionState; // @synthesize versionState;
@property(copy, nonatomic) NSString *appid; // @synthesize appid;
- (void).cxx_destruct;

@end

