//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "CNetworkStatusExt.h"
#import "MMKernelExt.h"
#import "MMService.h"
#import "PBMessageObserverDelegate.h"

@class NSString, NSTimer;

@interface CheckMobileSIMType : MMService <CNetworkStatusExt, MMService, MMKernelExt, PBMessageObserverDelegate>
{
    _Bool hasGetSimType;
    unsigned int businessFlag;
    unsigned int productType;
    unsigned int simType;
    unsigned long long lastCheckMobileSIMTypeTime;
    unsigned long long cacheExpiredTime;
    NSTimer *timer;
    NSString *simCardIp;
}

+ (int)GetCarrierType;
- (void).cxx_destruct;
- (void)onSimCardNetTypeChange;
- (void)ReachabilityChange:(unsigned int)arg1;
- (void)autoUpdate;
- (void)NotifyWKTypeChange:(unsigned int)arg1 reason:(int)arg2;
- (void)NotifySimTypeChange:(unsigned int)arg1 reason:(int)arg2;
- (_Bool)isUnicomNetwork;
- (id)getIPAddresses;
- (id)getIPAddress;
- (id)GetIDFV;
- (id)GetIDFA;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)Check:(int)arg1;
- (_Bool)ParseSIMType:(int)arg1 flag:(unsigned int)arg2;
- (int)GetWKType;
- (int)GetSIMType:(int)arg1;
- (void)onAuthOK;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

