//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EmoticonViewWithPreview.h"

@class MMBadgeView, UIImage;

@interface EmoticonBoardButton : EmoticonViewWithPreview
{
    MMBadgeView *m_badgeView;
    UIImage *m_buttonImage;
    unsigned long long m_type;
}

@property(nonatomic) unsigned long long type; // @synthesize type=m_type;
@property(retain, nonatomic) UIImage *buttonImage; // @synthesize buttonImage=m_buttonImage;
- (void).cxx_destruct;
- (void)updateAccessibilityLabelWithDes:(id)arg1;
- (void)updateDesc;
- (void)configBadgeWithNeedShowNew:(_Bool)arg1;
- (void)hidePreview;
- (void)hideFocusView;
- (void)showFocusView;
- (void)showPreview;
- (void)initView;

@end

