//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CameraVideoDeviceDelegate.h"

@class CameraReflectDevice, NSString;

@interface FaceRecogCheckBrightnessLogic : NSObject <CameraVideoDeviceDelegate>
{
    _Bool _hasCheckBrightness;
    float _lightThreshold;
    id <FaceRecogCheckBrightnessLogicDelegate> _delegate;
    CameraReflectDevice *_lightDetector;
}

@property(retain, nonatomic) CameraReflectDevice *lightDetector; // @synthesize lightDetector=_lightDetector;
@property(nonatomic) _Bool hasCheckBrightness; // @synthesize hasCheckBrightness=_hasCheckBrightness;
@property(nonatomic) float lightThreshold; // @synthesize lightThreshold=_lightThreshold;
@property(nonatomic) __weak id <FaceRecogCheckBrightnessLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (float)getBrightness:(struct opaqueCMSampleBuffer *)arg1;
- (void)startCheck;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

