//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCTTableCoding.h"

@class NSString;

@interface FavoritesCDNInfo : NSObject <WCTTableCoding>
{
    unsigned int localItemId;
    unsigned int size;
    int status;
    int isThumb;
    int dataType;
    unsigned int IntRes1;
    unsigned int IntRes2;
    NSString *localDataID;
    NSString *cdnUrl;
    NSString *cdnKey;
    NSString *md5;
    NSString *head256Md5;
    NSString *streamId;
    NSString *dataFmt;
    NSString *clientMsgID;
    NSString *StrRes1;
    NSString *StrRes2;
}

+ (void)__wcdb_FavoritesCDNInfo_index_26:(struct WCTBinding *)arg1;
+ (void)__wcdb_FavoritesCDNInfo_index_25:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)StrRes2;
+ (void)__wcdb_FavoritesCDNInfo_synthesize_24:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)StrRes1;
+ (void)__wcdb_FavoritesCDNInfo_synthesize_23:(struct WCTBinding *)arg1;
+ (void)__wcdb_FavoritesCDNInfo_default_22:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)IntRes2;
+ (void)__wcdb_FavoritesCDNInfo_synthesize_21:(struct WCTBinding *)arg1;
+ (void)__wcdb_FavoritesCDNInfo_default_20:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)IntRes1;
+ (void)__wcdb_FavoritesCDNInfo_synthesize_19:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)clientMsgID;
+ (void)__wcdb_FavoritesCDNInfo_synthesize_18:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)dataFmt;
+ (void)__wcdb_FavoritesCDNInfo_synthesize_17:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)streamId;
+ (void)__wcdb_FavoritesCDNInfo_synthesize_16:(struct WCTBinding *)arg1;
+ (void)__wcdb_FavoritesCDNInfo_default_15:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)dataType;
+ (void)__wcdb_FavoritesCDNInfo_synthesize_14:(struct WCTBinding *)arg1;
+ (void)__wcdb_FavoritesCDNInfo_default_13:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)isThumb;
+ (void)__wcdb_FavoritesCDNInfo_synthesize_12:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)head256Md5;
+ (void)__wcdb_FavoritesCDNInfo_synthesize_11:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)md5;
+ (void)__wcdb_FavoritesCDNInfo_synthesize_10:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)cdnKey;
+ (void)__wcdb_FavoritesCDNInfo_synthesize_9:(struct WCTBinding *)arg1;
+ (void)__wcdb_FavoritesCDNInfo_default_8:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)status;
+ (void)__wcdb_FavoritesCDNInfo_synthesize_7:(struct WCTBinding *)arg1;
+ (void)__wcdb_FavoritesCDNInfo_default_6:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)size;
+ (void)__wcdb_FavoritesCDNInfo_synthesize_5:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)cdnUrl;
+ (void)__wcdb_FavoritesCDNInfo_synthesize_4:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)localDataID;
+ (void)__wcdb_FavoritesCDNInfo_synthesize_3:(struct WCTBinding *)arg1;
+ (void)__wcdb_FavoritesCDNInfo_default_2:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)localItemId;
+ (void)__wcdb_FavoritesCDNInfo_synthesize_1:(struct WCTBinding *)arg1;
+ (CDUnknownBlockType)columnNamed;
+ (const struct All *)allResults;
+ (const struct WCTPropertyList *)allProperties;
+ (const struct WCTBinding *)objectRelationalMapping;
@property(retain, nonatomic) NSString *StrRes2; // @synthesize StrRes2;
@property(retain, nonatomic) NSString *StrRes1; // @synthesize StrRes1;
@property(nonatomic) unsigned int IntRes2; // @synthesize IntRes2;
@property(nonatomic) unsigned int IntRes1; // @synthesize IntRes1;
@property(retain, nonatomic) NSString *clientMsgID; // @synthesize clientMsgID;
@property(retain, nonatomic) NSString *dataFmt; // @synthesize dataFmt;
@property(retain, nonatomic) NSString *streamId; // @synthesize streamId;
@property(nonatomic) int dataType; // @synthesize dataType;
@property(nonatomic) int isThumb; // @synthesize isThumb;
@property(retain, nonatomic) NSString *head256Md5; // @synthesize head256Md5;
@property(retain, nonatomic) NSString *md5; // @synthesize md5;
@property(retain, nonatomic) NSString *cdnKey; // @synthesize cdnKey;
@property(nonatomic) int status; // @synthesize status;
@property(nonatomic) unsigned int size; // @synthesize size;
@property(retain, nonatomic) NSString *cdnUrl; // @synthesize cdnUrl;
@property(retain, nonatomic) NSString *localDataID; // @synthesize localDataID;
@property(nonatomic) unsigned int localItemId; // @synthesize localItemId;
- (void).cxx_destruct;
- (id)init;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

