//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class MMUILabel, SightIconView, UIImage, UIImageView, WCPlayerConfigControlView, WCPlayerInfo, WCPlayerView;

@interface FavSimpleSightView : MMUIView
{
    WCPlayerView *m_sightView;
    WCPlayerConfigControlView *m_controlView;
    WCPlayerInfo *m_playerInfo;
    MMUILabel *m_hintLabel;
    SightIconView *m_hintIconView;
    SightIconView *m_fakePlayButtom;
    UIImageView *m_fakeThumbView;
    double m_iconRadius;
    _Bool m_bFullScreen;
    UIImage *m_thumbImage;
}

- (void).cxx_destruct;
- (void)resizeHint;
- (void)hideHintView;
- (void)showHintView;
- (void)showHint:(id)arg1;
- (void)setIconViewRadius:(double)arg1;
- (void)setProgress:(double)arg1;
- (void)setLoadingState:(_Bool)arg1;
- (void)setIconViewHidden:(_Bool)arg1;
- (void)setToolViewHidden:(_Bool)arg1;
- (void)setThumbImageHidden:(_Bool)arg1;
- (void)setVideoPath:(id)arg1;
- (void)refreshThumb;
- (void)setThumbImage:(id)arg1;
- (void)setThumbImagePath:(id)arg1;
- (void)clearPlayer;
- (void)stopPlayer;
- (void)pauseVideo;
- (void)playVideo;
- (void)startPlayer;
- (void)setFrame:(struct CGRect)arg1;
- (void)setSightDelegate:(id)arg1;
- (void)setFakeViewHidden:(_Bool)arg1;
- (void)initFakeView;
- (id)initWithFrame:(struct CGRect)arg1 VideoPath:(id)arg2 FullScreenMode:(_Bool)arg3 AutoPlay:(_Bool)arg4;

@end

