//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCTTableCoding.h"

@class NSString;

@interface FavTag : NSObject <WCTTableCoding>
{
    unsigned int _localId;
    NSString *_tag;
}

+ (void)__wcdb_FavTag_index_46:(struct WCTBinding *)arg1;
+ (void)__wcdb_FavTag_index_45:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)tag;
+ (void)__wcdb_FavTag_synthesize_44:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)localId;
+ (void)__wcdb_FavTag_synthesize_43:(struct WCTBinding *)arg1;
+ (CDUnknownBlockType)columnNamed;
+ (const struct All *)allResults;
+ (const struct WCTPropertyList *)allProperties;
+ (const struct WCTBinding *)objectRelationalMapping;
@property(retain, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(nonatomic) unsigned int localId; // @synthesize localId=_localId;
- (void).cxx_destruct;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

