//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class ImageViewData, NSString, TextViewData;

@interface ImageWithDescViewData : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) int align; // @dynamic align;
@property(retain, nonatomic) TextViewData *desc; // @dynamic desc;
@property(retain, nonatomic) ImageViewData *image; // @dynamic image;
@property(nonatomic) int position; // @dynamic position;
@property(retain, nonatomic) NSString *viewId; // @dynamic viewId;

@end

