//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMVoidCallback, NSString;

@interface KindaRichLabelViewV2TextFragment : NSObject
{
    NSString *_m_text;
    long long _m_color;
    MMVoidCallback *_m_callback;
    long long _m_linkStyle;
    struct _NSRange _m_range;
}

@property(nonatomic) long long m_linkStyle; // @synthesize m_linkStyle=_m_linkStyle;
@property(nonatomic) struct _NSRange m_range; // @synthesize m_range=_m_range;
@property(nonatomic) MMVoidCallback *m_callback; // @synthesize m_callback=_m_callback;
@property(nonatomic) long long m_color; // @synthesize m_color=_m_color;
@property(nonatomic) NSString *m_text; // @synthesize m_text=_m_text;
- (long long)getLinkStyle;
- (id)getCallback;
- (long long)getColor;
- (struct _NSRange)getRange;
- (id)getText;
- (id)initWithText:(id)arg1 range:(struct _NSRange)arg2 color:(long long)arg3 callback:(id)arg4 linkStyle:(long long)arg5;

@end

