//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "NSCopying.h"

@class MailRTEImageInfo, MailRTEListInfo, MailRTELocationInfo;

@interface MailRTEAttachmentInfo : MMObject <NSCopying>
{
    MailRTELocationInfo *_locationInfo;
    MailRTEImageInfo *_imageInfo;
    MailRTEListInfo *_listInfo;
}

@property(retain, nonatomic) MailRTEListInfo *listInfo; // @synthesize listInfo=_listInfo;
@property(retain, nonatomic) MailRTEImageInfo *imageInfo; // @synthesize imageInfo=_imageInfo;
@property(retain, nonatomic) MailRTELocationInfo *locationInfo; // @synthesize locationInfo=_locationInfo;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

