//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface MMRTCMenuResponder : NSObject
{
    _Bool _disableLongPress;
    id <MMRTCMenuSelectDelegate> _selectDelegate;
    id <MMRTCMenuResponderDelegate> _responderDelegate;
    NSArray *_originMenuItems;
}

@property(retain, nonatomic) NSArray *originMenuItems; // @synthesize originMenuItems=_originMenuItems;
@property(nonatomic) _Bool disableLongPress; // @synthesize disableLongPress=_disableLongPress;
@property(nonatomic) __weak id <MMRTCMenuResponderDelegate> responderDelegate; // @synthesize responderDelegate=_responderDelegate;
@property(nonatomic) __weak id <MMRTCMenuSelectDelegate> selectDelegate; // @synthesize selectDelegate=_selectDelegate;
- (void).cxx_destruct;
- (void)onMenuHidden;
- (id)getSelectMenuItem;
- (id)getMenuActionResponder:(SEL)arg1;
- (_Bool)canRespondsToMenuAction:(SEL)arg1;
- (void)onSelectAllText:(id)arg1;
- (void)onSelectTextCopy:(id)arg1;
- (void)onSelectTextForward:(id)arg1;

@end

