//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMWebPopInteractiveTransition;

@protocol MMWebPopInteractiveTransitionDelegate <NSObject>

@optional
- (_Bool)onPopBackInteractiveRecognizeEdgeGesture;
- (void)onPopBackInteractiveTransitionEnd:(MMWebPopInteractiveTransition *)arg1 isComplete:(_Bool)arg2;
- (void)onPopBackInteractiveTransitionChange:(MMWebPopInteractiveTransition *)arg1;
- (void)onPopBackInteractiveTransitionBegin:(MMWebPopInteractiveTransition *)arg1;
@end

