//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBMessageObserverDelegate.h"

@class NSString;

@interface NormalContactVerifyLogic : NSObject <PBMessageObserverDelegate>
{
    unsigned int _m_qrAddScene;
    id <NormalContactVerifyLogicDelegate> _delegate;
    NSString *_m_reportInfo;
}

@property(retain, nonatomic) NSString *m_reportInfo; // @synthesize m_reportInfo=_m_reportInfo;
@property(nonatomic) unsigned int m_qrAddScene; // @synthesize m_qrAddScene=_m_qrAddScene;
@property(nonatomic) __weak id <NormalContactVerifyLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)HandleVerifyUser:(id)arg1;
- (void)HandleGetContact:(id)arg1;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (_Bool)sendVerifyUserRequest:(id)arg1;
- (_Bool)doubleCheckContactAntispamTickets:(id)arg1 withRequest:(id)arg2;
- (_Bool)startVerifyContact:(id)arg1 opcode:(unsigned int)arg2 verifyMsg:(id)arg3;
- (void)dealloc;

@end

