//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QBJceObjectV2.h"

@class NSString;

@interface QBPreferencesKeyValue : QBJceObjectV2
{
    NSString *jcev2_p_0_o_sKey;
    NSString *jcev2_p_1_o_sValue;
}

+ (id)jceType;
+ (void)initialize;
@property(retain, nonatomic, getter=sValue, setter=setSValue:) NSString *jcev2_p_1_o_sValue; // @synthesize jcev2_p_1_o_sValue;
@property(retain, nonatomic, getter=sKey, setter=setSKey:) NSString *jcev2_p_0_o_sKey; // @synthesize jcev2_p_0_o_sKey;
- (void).cxx_destruct;
- (id)init;

@end

