//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextViewDelegate.h"

@class NSArray, NSDictionary, NSString, RTEAttachmentReuseableView, RTEBaseTextView, RTEImageTextAttachment, RTETextAttachment, UIImage;

@protocol RTEBaseTextViewDelegate <UITextViewDelegate>

@optional
- (RTEImageTextAttachment *)textView:(RTEBaseTextView *)arg1 requestAttachmentWithImage:(UIImage *)arg2;
- (void)textView:(RTEBaseTextView *)arg1 didChangeTypingAttributes:(NSDictionary *)arg2;
- (void)textView:(RTEBaseTextView *)arg1 didDeleteAttachments:(NSArray *)arg2;
- (void)textView:(RTEBaseTextView *)arg1 willDeleteAttachments:(NSArray *)arg2;
- (_Bool)textView:(RTEBaseTextView *)arg1 shouldChangeAttachments:(NSArray *)arg2 andTextInRange:(struct _NSRange)arg3 replacementText:(NSString *)arg4;
- (RTEAttachmentReuseableView *)textView:(RTEBaseTextView *)arg1 attachmentViewWithAttachment:(RTETextAttachment *)arg2;
@end

