//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RTEConfigure : NSObject
{
}

+ (double)getIOSVersion;
+ (_Bool)floatVal:(double)arg1 isEqualTo:(double)arg2;
+ (id)contentDefaultParagraphStyle;
+ (id)contentDefaultTextAttribute;
+ (id)attachmentsClassLookupTable;

@end

