//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "IMsgExt.h"
#import "StrongNotificationViewControllerDelegate.h"

@class NSString, StrongNotificationViewController;

@interface StrongNotificationExclusiveMsgLogic : MMObject <StrongNotificationViewControllerDelegate, IMsgExt>
{
    StrongNotificationViewController *m_strongNotificationViewController;
    id <StrongNotificationExclusiveMsgLogicDelegate> m_delegate;
}

@property(nonatomic) __weak id <StrongNotificationExclusiveMsgLogicDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (void)OnAddMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)setStrongNotificationItemAndMessageStatueHadShow:(id)arg1;
- (void)onClickIKonwButton:(id)arg1;
- (id)p_getStrongNotificationViewController;
- (id)p_getExclusiveMsgQueue;
- (void)processMsg:(id)arg1;
- (void)p_internalCheckMsgQueue;
- (void)onFromBackgroundToForeground;
- (_Bool)isWindowShowing;
- (void)closeStrongNotificationView:(id)arg1;
- (void)checkMsgQueue;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

