//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"
#import "PBMessageObserverDelegate.h"

@class NSString;

@interface WABackgroundFetchMgr : MMService <MMService, PBMessageObserverDelegate>
{
}

- (id)getPreFetchData:(id)arg1;
- (void)tryDeleteExpiredData;
- (void)handlePeriodFetchResponse:(id)arg1;
- (void)handlePreFetchResponse:(id)arg1 Request:(id)arg2;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (_Bool)asyncPreFetchDataIfNeed:(id)arg1 RelativeURL:(id)arg2 EnterScene:(unsigned int)arg3;
- (void)periodFetchData:(id)arg1;
- (id)getFilteredListIfNotExceedTime:(id)arg1;
- (id)getRecentUseMyStarWeAppList;
- (void)fetchPeriodData;
- (void)onServiceEnterForeground;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

