//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CContact, GetProfileInfoResponse_WxaEvaluateBasicInfo, MMUIButton, MMUIView, MMWebImageView, UILabel;

@interface WAProfileHeaderView : UIView
{
    CContact *_contact;
    GetProfileInfoResponse_WxaEvaluateBasicInfo *_basicInfo;
    MMWebImageView *_avatarView;
    UILabel *_nameLabel;
    UILabel *_descLabel;
    MMUIButton *_originalButton;
    MMUIButton *_enterButton;
    MMUIButton *_shareButton;
    MMUIView *_buttonSplitView;
    id <WAProfileHeaderViewDelegate> _delegate;
}

@property(nonatomic) __weak id <WAProfileHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)updateContact:(id)arg1;
- (void)updateEvaluateBasicInfo:(id)arg1;
- (void)onShareButtonClicked;
- (void)onEnterButtonClicked;
- (void)onOriginalButtonClicked;
- (void)onUnhighlightBorder:(id)arg1;
- (void)onHighlightBorder:(id)arg1;
- (void)setupSubviews;
- (id)initWithContact:(id)arg1;

@end

