//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "IWAProfileServiceExt.h"
#import "WAContactMgrExtension.h"

@class CContact, GetProfileInfoResponse, NSMutableArray, NSMutableDictionary, NSString;

@interface WAProfileLogicController : MMObject <IWAProfileServiceExt, WAContactMgrExtension>
{
    NSString *_userName;
    NSMutableArray *_sectionList;
    NSMutableDictionary *_sectonType2RowNum;
    CDUnknownBlockType _requestProfileDataCompleteBlock;
    _Bool _bProfileResponseDataReturned;
    GetProfileInfoResponse *_profileResponseData;
    CContact *_contact;
}

@property _Bool bProfileResponseDataReturned; // @synthesize bProfileResponseDataReturned=_bProfileResponseDataReturned;
@property(retain, nonatomic) CContact *contact; // @synthesize contact=_contact;
@property(retain, nonatomic) GetProfileInfoResponse *profileResponseData; // @synthesize profileResponseData=_profileResponseData;
- (void).cxx_destruct;
- (id)feedBack;
- (id)friendLikeList;
- (id)relatedBrandList;
- (id)previewMediaList;
- (id)evaluateBasicInfo;
- (long long)numberOfSections;
- (unsigned int)typeOfSection:(long long)arg1;
- (void)reloadSections;
- (void)tryNotifyProfileDataReady;
- (void)onFetchProfileInfo:(id)arg1 userName:(id)arg2;
- (void)requestProfileData:(CDUnknownBlockType)arg1;
- (void)onModifyWeAppContact:(id)arg1;
- (void)dealloc;
- (id)initWithUsername:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

