//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class MMUILabel, NSArray, UIImageView, WAHeaderStackDisplayView;

@interface WAProfileRelatedBrandCell : UITableViewCell
{
    MMUILabel *_titleLabel;
    MMUILabel *_descLabel;
    WAHeaderStackDisplayView *_headerStackView;
    UIImageView *_arrowView;
    NSArray *_brandInfoList;
    unsigned long long _showIconCount;
}

+ (double)cellHeight;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)updateRelatedBrandList:(id)arg1;
- (void)setupSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

