//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "MMWebImageViewDelegate.h"

@class MMWebImageView, NSData, NSString, UIActivityIndicatorView, UILabel;

@interface WASendSessionMsgView : UIView <MMWebImageViewDelegate>
{
    UILabel *_titleLabel;
    MMWebImageView *_imageView;
    UIActivityIndicatorView *_imageIndicatorView;
    NSString *_imageURL;
    NSData *_imageData;
    id <WASendSessionMsgViewDelegate> _viewDelegate;
}

@property(nonatomic) __weak id <WASendSessionMsgViewDelegate> viewDelegate; // @synthesize viewDelegate=_viewDelegate;
- (void).cxx_destruct;
- (void)onLoadImageOK:(id)arg1;
- (void)onClickCoverButton;
- (id)getHighlightImageWithImageViewFrame:(struct CGRect)arg1;
- (void)initCoverButton;
- (void)initImageView;
- (void)initTitleLabel;
- (void)initBackgroundImage;
- (void)initView;
- (id)getLoadedImageData;
- (void)updateImageURL:(id)arg1 imageData:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

