//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMUIViewController, WAAppCanvasWrapperView;

@interface WAWidgetJSEventHandler_BaseEvent : NSObject
{
    unsigned int _eventId;
    MMUIViewController *_viewController;
    WAAppCanvasWrapperView *_wrapperView;
    id <WAWidgetJSEventHandlerDelegate> _delegate;
}

@property(nonatomic) unsigned int eventId; // @synthesize eventId=_eventId;
@property(nonatomic) __weak id <WAWidgetJSEventHandlerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak WAAppCanvasWrapperView *wrapperView; // @synthesize wrapperView=_wrapperView;
@property(nonatomic) __weak MMUIViewController *viewController; // @synthesize viewController=_viewController;
- (void).cxx_destruct;
- (void)handleJSEvent:(id)arg1;
- (void)endWithResult:(id)arg1;

@end

