//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCTTableCoding.h"

@class NSString;

@interface WCDBMigrationMsgIDObject : NSObject <WCTTableCoding>
{
    NSString *m_fileName;
}

+ (void)__wcdb_WCDBMigrationMsgIDObject_primary_1:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)m_fileName;
+ (void)__wcdb_WCDBMigrationMsgIDObject_synthesize_0:(struct WCTBinding *)arg1;
+ (CDUnknownBlockType)columnNamed;
+ (const struct All *)allResults;
+ (const struct WCTPropertyList *)allProperties;
+ (const struct WCTBinding *)objectRelationalMapping;
@property(retain, nonatomic) NSString *m_fileName; // @synthesize m_fileName;
- (void).cxx_destruct;
- (id)description;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

