//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCTTableCoding.h"

@class NSString;

@interface WCDeviceAirKissReccord : NSObject <WCTTableCoding>
{
    unsigned int IntRes1;
    unsigned int IntRes2;
    NSString *m_key;
    NSString *m_data;
    NSString *StrRes1;
    NSString *StrRes2;
}

+ (const struct WCTProperty *)StrRes2;
+ (void)__wcdb_WCDeviceAirKissReccord_synthesize_21:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)StrRes1;
+ (void)__wcdb_WCDeviceAirKissReccord_synthesize_20:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)IntRes2;
+ (void)__wcdb_WCDeviceAirKissReccord_synthesize_19:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)IntRes1;
+ (void)__wcdb_WCDeviceAirKissReccord_synthesize_18:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)m_data;
+ (void)__wcdb_WCDeviceAirKissReccord_synthesize_17:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)m_key;
+ (void)__wcdb_WCDeviceAirKissReccord_synthesize_16:(struct WCTBinding *)arg1;
+ (CDUnknownBlockType)columnNamed;
+ (const struct All *)allResults;
+ (const struct WCTPropertyList *)allProperties;
+ (const struct WCTBinding *)objectRelationalMapping;
@property(retain, nonatomic) NSString *StrRes2; // @synthesize StrRes2;
@property(retain, nonatomic) NSString *StrRes1; // @synthesize StrRes1;
@property(nonatomic) unsigned int IntRes2; // @synthesize IntRes2;
@property(nonatomic) unsigned int IntRes1; // @synthesize IntRes1;
@property(retain, nonatomic) NSString *m_data; // @synthesize m_data;
@property(retain, nonatomic) NSString *m_key; // @synthesize m_key;
- (void).cxx_destruct;
- (void)dealloc;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

