//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "WCTTableCoding.h"

@interface WCDurationLogItem : MMObject <WCTTableCoding>
{
    _Bool isAutoIncrement;
    unsigned int localId;
    unsigned int activeStartTime;
    unsigned int activeEndTime;
    long long lastInsertedRowID;
}

+ (id)stringFromItems:(id)arg1;
+ (id)logItemFromDescription:(id)arg1;
+ (id)logItem;
+ (void)__wcdb_WCDurationLogItem_primary_3:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)activeEndTime;
+ (void)__wcdb_WCDurationLogItem_synthesize_2:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)activeStartTime;
+ (void)__wcdb_WCDurationLogItem_synthesize_1:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)localId;
+ (void)__wcdb_WCDurationLogItem_synthesize_0:(struct WCTBinding *)arg1;
+ (CDUnknownBlockType)columnNamed;
+ (const struct All *)allResults;
+ (const struct WCTPropertyList *)allProperties;
+ (const struct WCTBinding *)objectRelationalMapping;
@property(nonatomic) long long lastInsertedRowID; // @synthesize lastInsertedRowID;
@property(nonatomic) _Bool isAutoIncrement; // @synthesize isAutoIncrement;
@property(nonatomic) unsigned int activeEndTime; // @synthesize activeEndTime;
@property(nonatomic) unsigned int activeStartTime; // @synthesize activeStartTime;
@property(nonatomic) unsigned int localId; // @synthesize localId;
- (id)description;
- (void)reset;

@end

