//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IWCCardPkgExt.h"
#import "WCMktCardHomePageCgiDelegate.h"
#import "WCMktGetCardPkgMchInfoCgiDelegate.h"

@class GetMktCardHomePageResponse, NSMutableArray, NSString, WCMktCardHomePageCgi, WCMktDeleteMchInListCgi, WCMktGetCardPkgMchInfoCgi;

@interface WCMktCardHomeLogicController : NSObject <WCMktCardHomePageCgiDelegate, IWCCardPkgExt, WCMktGetCardPkgMchInfoCgiDelegate>
{
    _Bool _bHasSendHomePageRequest;
    _Bool _bIsLoadingMoreMktCardList;
    _Bool _bNeedUpdateMchInfoAfterViewControllerAppear;
    id <WCMktCardHomeLogicControllerDelegate> _delegate;
    GetMktCardHomePageResponse *_mktCardHomePageResponse;
    NSMutableArray *_sectionArray;
    NSMutableArray *_expandMerchatIDList;
    WCMktCardHomePageCgi *_homePageCgi;
    WCMktDeleteMchInListCgi *_deleteMchCgi;
    WCMktGetCardPkgMchInfoCgi *_getMchInfoCgi;
    NSString *_currentOpenMchID;
    NSString *_deletingCardID;
    NSString *_deletingMchID;
}

@property(retain, nonatomic) NSString *deletingMchID; // @synthesize deletingMchID=_deletingMchID;
@property(retain, nonatomic) NSString *deletingCardID; // @synthesize deletingCardID=_deletingCardID;
@property(retain, nonatomic) NSString *currentOpenMchID; // @synthesize currentOpenMchID=_currentOpenMchID;
@property(nonatomic) _Bool bNeedUpdateMchInfoAfterViewControllerAppear; // @synthesize bNeedUpdateMchInfoAfterViewControllerAppear=_bNeedUpdateMchInfoAfterViewControllerAppear;
@property(retain, nonatomic) WCMktGetCardPkgMchInfoCgi *getMchInfoCgi; // @synthesize getMchInfoCgi=_getMchInfoCgi;
@property(retain, nonatomic) WCMktDeleteMchInListCgi *deleteMchCgi; // @synthesize deleteMchCgi=_deleteMchCgi;
@property(nonatomic) _Bool bIsLoadingMoreMktCardList; // @synthesize bIsLoadingMoreMktCardList=_bIsLoadingMoreMktCardList;
@property(retain, nonatomic) WCMktCardHomePageCgi *homePageCgi; // @synthesize homePageCgi=_homePageCgi;
@property(nonatomic) _Bool bHasSendHomePageRequest; // @synthesize bHasSendHomePageRequest=_bHasSendHomePageRequest;
@property(retain, nonatomic) NSMutableArray *expandMerchatIDList; // @synthesize expandMerchatIDList=_expandMerchatIDList;
@property(retain, nonatomic) NSMutableArray *sectionArray; // @synthesize sectionArray=_sectionArray;
@property(retain, nonatomic) GetMktCardHomePageResponse *mktCardHomePageResponse; // @synthesize mktCardHomePageResponse=_mktCardHomePageResponse;
@property(nonatomic) __weak id <WCMktCardHomeLogicControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onGetCardPkgMchInfoCgiResp:(id)arg1;
- (void)sendGetMchInfoRequest:(id)arg1;
- (void)onGetWCMktCardHomePageCgiResp:(id)arg1;
- (void)onRetrieveLocation:(int)arg1;
- (void)getHomePageDataFromSvrWithOffset:(unsigned int)arg1;
- (void)getMoreHomePageDataFromSvr;
- (void)getHomePageDataFromSvr;
- (long long)getListSectionIndexWithSectionName:(id)arg1;
- (void)handleFaqItemClick;
- (void)handleClickElemData:(id)arg1;
- (void)handleClickMerchantAreaWithMerchantID:(id)arg1;
- (void)refreshHomePageDataFromSvr;
- (void)onDeleteCardIDList:(id)arg1 ErrCode:(int)arg2;
- (void)deleteCardWithCardData:(id)arg1 mchID:(id)arg2;
- (void)updateMerchantInfoAfterViewControllerWillAppearIfNeed;
- (void)updateMerchantInfoWithMchID:(id)arg1;
- (void)handleTinyAppOpenWithAppInfo:(id)arg1 needUpdateMchInfo:(_Bool)arg2;
- (void)handleMerchantItemCellClickCardItemTagBtnToOpenTinyApp:(id)arg1 merchantID:(id)arg2;
- (void)handleMerchantItemCellClickTagBtnToOpenTinyApp:(id)arg1 merchantID:(id)arg2;
- (void)handleTableViewDidSelectRowAtIndexPath:(id)arg1;
- (void)handleHomePageDataLoadingMore;
- (void)handleClickExpandOrCollapseBtnWithID:(id)arg1;
- (_Bool)isMerchantCardListExpandWithID:(id)arg1;
- (id)getLastItemIndexPath;
- (id)getHomePageFaqItem;
- (id)getHomePageElementWithMchID:(id)arg1;
- (id)getStoreListIndexPathWithMchID:(id)arg1;
- (id)getUnderStoreListSectionTitle;
- (id)getSectionNameWithSection:(long long)arg1;
- (id)getHomePageElementWithIndexPath:(id)arg1;
- (long long)getTableViewRowCountInSection:(long long)arg1;
- (long long)getTableViewSectionCount;
- (_Bool)hasRespData;
- (_Bool)isMktCardDataAllLoad;
- (_Bool)hasMktCardData;
- (id)getHomePageStoreListData;
- (void)saveHomePageDataToFile;
- (void)loadHomePageCacheDataAndRefreshFromSvr;
- (void)setupData;
- (id)initLogicControllerWithDelegate:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

