//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "ILinkEventExt.h"
#import "UITextFieldDelegate.h"
#import "WCActionSheetDelegate.h"
#import "WCPayBankListPanelViewDelegate.h"
#import "WCPayLQTOrderConfirmViewDelegate.h"
#import "WCPayLQTRedeemTypeCellDelegate.h"

@class MMTableView, MMUIButton, MMUILabel, NSString, RichTextView, UIButton, UIImageView, UILabel, UITextField, UIView, WCPayBankListPanelView, WCPayLQTOrderConfirmView, WCPayWebImageView;

@interface WCPayLQTMoneyViewController : WCPayBaseViewController <WCPayLQTRedeemTypeCellDelegate, UITextFieldDelegate, ILinkEventExt, WCPayLQTOrderConfirmViewDelegate, WCActionSheetDelegate, WCPayBankListPanelViewDelegate>
{
    _Bool _bCheckBoxSelect;
    _Bool _bNeedUpdatePurchData;
    unsigned int _m_selectedRedeemType;
    id <WCPayLQTMoneyViewControllerDelegate> _delegate;
    MMTableView *_tableView;
    UIButton *_operationBtn;
    UITextField *_moneyTextField;
    MMUILabel *_invalidTipsLabel;
    RichTextView *_richTextView;
    WCPayLQTOrderConfirmView *_confirmView;
    MMUIButton *_cardInfoBtn;
    WCPayBankListPanelView *_panelView;
    MMUIButton *_fetchTipsBtn;
    MMUILabel *_realtimeFetchBalanceTipsLabel;
    UIView *_m_buttonContentView;
    UIView *_m_protocolView;
    UIView *_m_profitView;
    UIView *_m_selectView;
    UIView *_m_inputContentView;
    UILabel *_m_topTipsLabel;
    UIView *_m_topbarView;
    UIButton *_m_maskTopbarButton;
    WCPayWebImageView *_m_cardLogo;
    UILabel *_m_availLabel;
    UILabel *_m_preArriveTimeLabel;
    UIImageView *_m_arrowImageView;
    UIView *_m_topbarLineView;
    UILabel *_m_textFieldTitle;
    UILabel *_m_unitLabel;
    UIView *_m_moneyLineView;
    UIView *_m_redeemTypeListView;
    double _m_keyboardHeight;
    RichTextView *_balanceUpgradeTextView;
}

@property(nonatomic) _Bool bNeedUpdatePurchData; // @synthesize bNeedUpdatePurchData=_bNeedUpdatePurchData;
@property(retain, nonatomic) RichTextView *balanceUpgradeTextView; // @synthesize balanceUpgradeTextView=_balanceUpgradeTextView;
@property(nonatomic) double m_keyboardHeight; // @synthesize m_keyboardHeight=_m_keyboardHeight;
@property(nonatomic) unsigned int m_selectedRedeemType; // @synthesize m_selectedRedeemType=_m_selectedRedeemType;
@property(retain, nonatomic) UIView *m_redeemTypeListView; // @synthesize m_redeemTypeListView=_m_redeemTypeListView;
@property(retain, nonatomic) UIView *m_moneyLineView; // @synthesize m_moneyLineView=_m_moneyLineView;
@property(retain, nonatomic) UILabel *m_unitLabel; // @synthesize m_unitLabel=_m_unitLabel;
@property(retain, nonatomic) UILabel *m_textFieldTitle; // @synthesize m_textFieldTitle=_m_textFieldTitle;
@property(retain, nonatomic) UIView *m_topbarLineView; // @synthesize m_topbarLineView=_m_topbarLineView;
@property(retain, nonatomic) UIImageView *m_arrowImageView; // @synthesize m_arrowImageView=_m_arrowImageView;
@property(retain, nonatomic) UILabel *m_preArriveTimeLabel; // @synthesize m_preArriveTimeLabel=_m_preArriveTimeLabel;
@property(retain, nonatomic) UILabel *m_availLabel; // @synthesize m_availLabel=_m_availLabel;
@property(retain, nonatomic) WCPayWebImageView *m_cardLogo; // @synthesize m_cardLogo=_m_cardLogo;
@property(retain, nonatomic) UIButton *m_maskTopbarButton; // @synthesize m_maskTopbarButton=_m_maskTopbarButton;
@property(retain, nonatomic) UIView *m_topbarView; // @synthesize m_topbarView=_m_topbarView;
@property(retain, nonatomic) UILabel *m_topTipsLabel; // @synthesize m_topTipsLabel=_m_topTipsLabel;
@property(retain, nonatomic) UIView *m_inputContentView; // @synthesize m_inputContentView=_m_inputContentView;
@property(retain, nonatomic) UIView *m_selectView; // @synthesize m_selectView=_m_selectView;
@property(retain, nonatomic) UIView *m_profitView; // @synthesize m_profitView=_m_profitView;
@property(retain, nonatomic) UIView *m_protocolView; // @synthesize m_protocolView=_m_protocolView;
@property(retain, nonatomic) UIView *m_buttonContentView; // @synthesize m_buttonContentView=_m_buttonContentView;
@property(nonatomic) _Bool bCheckBoxSelect; // @synthesize bCheckBoxSelect=_bCheckBoxSelect;
@property(retain, nonatomic) MMUILabel *realtimeFetchBalanceTipsLabel; // @synthesize realtimeFetchBalanceTipsLabel=_realtimeFetchBalanceTipsLabel;
@property(retain, nonatomic) MMUIButton *fetchTipsBtn; // @synthesize fetchTipsBtn=_fetchTipsBtn;
@property(retain, nonatomic) WCPayBankListPanelView *panelView; // @synthesize panelView=_panelView;
@property(retain, nonatomic) MMUIButton *cardInfoBtn; // @synthesize cardInfoBtn=_cardInfoBtn;
@property(retain, nonatomic) WCPayLQTOrderConfirmView *confirmView; // @synthesize confirmView=_confirmView;
@property(retain, nonatomic) RichTextView *richTextView; // @synthesize richTextView=_richTextView;
@property(retain, nonatomic) MMUILabel *invalidTipsLabel; // @synthesize invalidTipsLabel=_invalidTipsLabel;
@property(retain, nonatomic) UITextField *moneyTextField; // @synthesize moneyTextField=_moneyTextField;
@property(retain, nonatomic) UIButton *operationBtn; // @synthesize operationBtn=_operationBtn;
@property(retain, nonatomic) MMTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <WCPayLQTMoneyViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onWCPayLQTRedeemTypeCellClick:(id)arg1;
- (id)currentRedeemTypeList;
- (_Bool)isBalanceSelected;
- (_Bool)isSaveScene;
- (void)updateTableViewOffset;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (id)navigationBarBackgroundColor;
- (void)fetchTipsBtnClick;
- (_Bool)hasFetchTipsContent;
- (void)onBankListPanelViewClickAddNewCardCell;
- (void)onBankListPanelViewClickForbidUrl:(id)arg1;
- (void)onBankListPanelViewReturnWithSelectedCardBindSerial:(id)arg1;
- (void)onBankListPanelViewCancel;
- (id)getPanelViewAddNewCardCellWording;
- (id)getPanelViewDescWording;
- (id)getPanelViewTitleWording;
- (unsigned int)getCurrentFetchTotalAmount;
- (id)getCurrentSelcectBankInfo;
- (id)setBalanceAsDefaultFetchCard;
- (id)setBalanceAsDefaultSaveCard;
- (id)getBalanceCardInfo;
- (id)getPanelViewBankList;
- (id)getCurrentCardList;
- (id)getCardNameWithBindSerial:(id)arg1;
- (_Bool)shouldShowProfitWording;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)checkBtnClick:(id)arg1;
- (id)makeProtocolContentView;
- (_Bool)lqtProtocolCheck;
- (_Bool)canShowLQTProtocol;
- (void)onOrderConfirmViewPayWithEnPwd:(id)arg1;
- (void)onOrderConfirmViewCancel;
- (void)cardInfoBtnClick;
- (void)refreshMoneyBottomTipsArea;
- (void)reloadContentView;
- (void)showPwdConfirmViewWhenPreRedeemFundOk;
- (void)checkIfSaveAmountInvalid:(unsigned int)arg1;
- (void)checkIfFetchAmountInvalid:(unsigned int)arg1;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)checkBtnStatus;
- (void)textFieldDidChang:(id)arg1;
- (void)operationBtnClick;
- (void)leftBarButtonClick;
- (void)showBalanceUpgradeTextView;
- (void)hideInvalidTipsLabel;
- (void)showInvalidTipsLabelWithContent:(id)arg1;
- (void)initInvalidTipsLabel;
- (void)makeBtnCellContentView:(id)arg1;
- (void)makeInputContentView:(id)arg1;
- (double)inputContentViewTopbarheight;
- (double)tableViewSaveAndFetchDetailTipsContentHeight;
- (double)saveAndFetchDetailTipsContentMaxWidth;
- (double)tableViewProfitContentHeight;
- (double)tableViewBtnWithProtocolCellHeight;
- (double)tableViewBtnCellHeight;
- (double)tableViewInputContentCellHeight;
- (void)setupContentView;
- (void)viewDidLoad;
- (void)updateRedeemTypeListView;
- (void)updateRedeemTypeSelection;
- (void)adjustButtonY;
- (void)updateView;
- (void)viewDidTransitionToNewSize;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

