//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayControlLogic.h"

#import "FaceRecogPayHandlerDelegate.h"
#import "WCPayFillCredInfoViewControllerDelegate.h"
#import "WCPayGenDigitalCertCgiDelegate.h"
#import "WCPayPayPwdViewControllerDelegate.h"
#import "WCPayResetPwdBindCardViewControllerDelegate.h"
#import "WCPayResetPwdBindedCardListViewControllerDelegate.h"
#import "WCPayResetPwdByFaceCgiDelegate.h"
#import "WCPayResetPwdCardInfoViewControllerDelegate.h"
#import "WCPayResetSelectVerifyWayViewControllerDelegate.h"
#import "WCPayVerifyPayCardViewControllerDelegate.h"
#import "WCPayVerifyUserRealNameInfoCgiDelegate.h"

@class FaceRecogPayHandler, NSString, WCPayGenDigitalCertCgi, WCPayResetPwdByFaceCgi, WCPayVerifyUserRealNameInfoCgi;

@interface WCPayResetPayPwdLogic : WCPayControlLogic <WCPayFillCredInfoViewControllerDelegate, WCPayResetSelectVerifyWayViewControllerDelegate, WCPayVerifyUserRealNameInfoCgiDelegate, WCPayResetPwdByFaceCgiDelegate, WCPayGenDigitalCertCgiDelegate, FaceRecogPayHandlerDelegate, WCPayResetPwdCardInfoViewControllerDelegate, WCPayVerifyPayCardViewControllerDelegate, WCPayPayPwdViewControllerDelegate, WCPayResetPwdBindedCardListViewControllerDelegate, WCPayResetPwdBindCardViewControllerDelegate>
{
    _Bool _bIsResetingPwdByFaceRecog;
    WCPayVerifyUserRealNameInfoCgi *_verifyRealnameInfoCgi;
    WCPayResetPwdByFaceCgi *_resetPwdByFaceCgi;
    WCPayGenDigitalCertCgi *_genDigitalCertCgi;
    FaceRecogPayHandler *_faceHandler;
    NSString *_faceAuthToken;
    NSString *_userName;
    NSString *_userIDType;
    NSString *_userIDNum;
}

@property(retain, nonatomic) NSString *userIDNum; // @synthesize userIDNum=_userIDNum;
@property(retain, nonatomic) NSString *userIDType; // @synthesize userIDType=_userIDType;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(nonatomic) _Bool bIsResetingPwdByFaceRecog; // @synthesize bIsResetingPwdByFaceRecog=_bIsResetingPwdByFaceRecog;
@property(retain, nonatomic) NSString *faceAuthToken; // @synthesize faceAuthToken=_faceAuthToken;
@property(retain, nonatomic) FaceRecogPayHandler *faceHandler; // @synthesize faceHandler=_faceHandler;
@property(retain, nonatomic) WCPayGenDigitalCertCgi *genDigitalCertCgi; // @synthesize genDigitalCertCgi=_genDigitalCertCgi;
@property(retain, nonatomic) WCPayResetPwdByFaceCgi *resetPwdByFaceCgi; // @synthesize resetPwdByFaceCgi=_resetPwdByFaceCgi;
@property(retain, nonatomic) WCPayVerifyUserRealNameInfoCgi *verifyRealnameInfoCgi; // @synthesize verifyRealnameInfoCgi=_verifyRealnameInfoCgi;
- (void).cxx_destruct;
- (void)faceRecogPayHandlerDidFinish:(id)arg1;
- (void)faceRecogPayHandlerDidCancel:(id)arg1;
- (void)clickResetPwdErrorAlert;
- (void)onGetResetPwdByFaceCgiResp:(id)arg1;
- (void)sendResetPwdByFaceRequest:(id)arg1;
- (void)continueLogicAfterHandleDigitalCertSucc;
- (void)onWCPayGenDigitalCertCgiWithResp:(id)arg1;
- (void)sendGenDigitalCertRequest;
- (void)onGetVerifyUserRealNameInfoCgiResp:(id)arg1;
- (void)onSelectVerifyWayViewControllerSelectVerifyFace;
- (void)onSelectVerifyWayViewControllerSelectVerifyCard;
- (void)onSelectVerifyWayViewControllerBack;
- (void)onFillCredInfoViewControllerConfirmWithName:(id)arg1 credType:(id)arg2 credNum:(id)arg3;
- (void)onFillCredInfoViewControllerBack;
- (void)OnHandleVerifiedSMSString:(id)arg1;
- (void)OnGetAvailableBank:(id)arg1 Error:(id)arg2;
- (void)OnGetBindingCardBin:(id)arg1 Error:(id)arg2;
- (void)OnGetBindingCardBin:(id)arg1 AvailableBank:(id)arg2 userExInfoResponse:(id)arg3 Error:(id)arg4;
- (void)OnGetBindQueryInfo:(id)arg1 Error:(id)arg2;
- (void)OnSetWCPayPasswordInReset:(id)arg1;
- (void)showResetPwdViewController;
- (void)OnResetWCPayPasswordVerifySMS:(id)arg1;
- (void)OnResetWCPayPasswordVerifyCard:(id)arg1 Error:(id)arg2;
- (void)OnWCPayResetPwdBindCardBack;
- (void)OnWCPayResetPwdBindCardNext;
- (void)OnResetPwdBindedCardListNext;
- (void)OnResetPwdBindedCardListBack;
- (void)OnResetPwdBindedCardListNewCardClicked;
- (_Bool)OnSelectBindCardAvailble:(id)arg1;
- (void)openNewCardErrorPathWebView;
- (void)PayPwdRightActionBack;
- (void)PayPwdBack;
- (void)SetPayPwdNext:(id)arg1;
- (void)VerifyPayPwdNext:(id)arg1;
- (void)showGiveUpResetAlert;
- (void)OnAlertGiveUpResetPwd;
- (void)VerifyPayCardAgain:(id)arg1;
- (void)VerifyPayCardNext:(id)arg1;
- (void)VerifyPayCardBack;
- (void)ResetPwdCardInfoPoped;
- (void)stopLogic;
- (void)ResetPwdCardInfoReadAgreement;
- (void)ResetPwdCardInfoNext:(id)arg1;
- (void)ResetPwdCardInfoCardInfoCancel;
- (void)onErrorAlertViewDismiss:(id)arg1;
- (void)BackToRootView;
- (void)startLogic;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

