//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton;

@interface WCRoundSelectionButton : UIView
{
    UIButton *_button;
    SEL _clickAction;
    id _clickTarget;
}

@property(nonatomic) __weak id clickTarget; // @synthesize clickTarget=_clickTarget;
@property(nonatomic) SEL clickAction; // @synthesize clickAction=_clickAction;
@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
- (void).cxx_destruct;
- (void)didClick:(id)arg1;
- (void)setSelected:(_Bool)arg1;
- (void)addTarget:(id)arg1 clickAction:(SEL)arg2;
- (void)layoutSubviews;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;

@end

