//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "WCFacadeExt.h"

@class MMTableViewInfo, NSString, WCOpLog;

@interface WCSetPermissionsViewController : MMUIViewController <WCFacadeExt>
{
    int _scene;
    id <WCSetPermissionsViewControllerDelegate> _delegate;
    NSString *_userName;
    WCOpLog *_wcOpLog;
    MMTableViewInfo *_tableViewInfo;
}

@property(retain, nonatomic) MMTableViewInfo *tableViewInfo; // @synthesize tableViewInfo=_tableViewInfo;
@property(retain, nonatomic) WCOpLog *wcOpLog; // @synthesize wcOpLog=_wcOpLog;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(nonatomic) int scene; // @synthesize scene=_scene;
@property(nonatomic) __weak id <WCSetPermissionsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onWCGroupRemoveMemberReturn:(_Bool)arg1 group:(id)arg2;
- (void)onWCGroupAddMemberReturn:(_Bool)arg1 group:(id)arg2;
- (void)onWCGroupModMemberReturn:(_Bool)arg1 group:(id)arg2;
- (void)becomeWCBlacklist:(_Bool)arg1;
- (void)becomeOutsider:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)opWCBlacklist:(id)arg1;
- (void)opOutsider:(id)arg1;
- (void)addPermissionSection;
- (void)reloadTableView;
- (void)initView;
- (void)viewDidLoad;
- (void)onDissmiss;
- (void)dealloc;
- (id)initWithUserName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

