//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class MMCPLabel, MMHeadImageView;

@interface WCStoryPreviewContactIndicatorCell : UICollectionViewCell
{
    MMHeadImageView *_headImageView;
    MMCPLabel *_usernameLabel;
}

@property(retain, nonatomic) MMCPLabel *usernameLabel; // @synthesize usernameLabel=_usernameLabel;
@property(retain, nonatomic) MMHeadImageView *headImageView; // @synthesize headImageView=_headImageView;
- (void).cxx_destruct;
- (void)setContact:(id)arg1;

@end

