//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IClearDataMgrExt.h"
#import "MMService.h"
#import "WCPlayerDownloadMgrInterface.h"
#import "WCStoryCommentUploadMgrDelegate.h"
#import "WCStoryUploadCdnMgrDelegate.h"

@class NSRecursiveLock, NSString, WCStoryCommentUploadMgr, WCStoryDataMgr, WCStoryDownloadImageCdnMgr, WCStoryDownloadVideoCdnMgr, WCStoryPostLimitObj, WCStorySetting, WCStoryUploadCdnMgr;

@interface WCStoryFacade : MMService <WCStoryUploadCdnMgrDelegate, WCStoryCommentUploadMgrDelegate, IClearDataMgrExt, MMService, WCPlayerDownloadMgrInterface>
{
    WCStoryDataMgr *_dataMgr;
    WCStoryUploadCdnMgr *_uploadMgr;
    WCStoryCommentUploadMgr *_commentUploadMgr;
    WCStoryDownloadVideoCdnMgr *_downloadVideoCdnMgr;
    WCStoryDownloadImageCdnMgr *_downloadImageCdnMgr;
    WCStoryPostLimitObj *_limitObj;
    WCStorySetting *_storySetting;
    NSRecursiveLock *_lock;
}

@property(retain, nonatomic) NSRecursiveLock *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) WCStorySetting *storySetting; // @synthesize storySetting=_storySetting;
@property(retain, nonatomic) WCStoryPostLimitObj *limitObj; // @synthesize limitObj=_limitObj;
@property(retain, nonatomic) WCStoryDownloadImageCdnMgr *downloadImageCdnMgr; // @synthesize downloadImageCdnMgr=_downloadImageCdnMgr;
@property(retain, nonatomic) WCStoryDownloadVideoCdnMgr *downloadVideoCdnMgr; // @synthesize downloadVideoCdnMgr=_downloadVideoCdnMgr;
@property(retain, nonatomic) WCStoryCommentUploadMgr *commentUploadMgr; // @synthesize commentUploadMgr=_commentUploadMgr;
@property(retain, nonatomic) WCStoryUploadCdnMgr *uploadMgr; // @synthesize uploadMgr=_uploadMgr;
@property(retain, nonatomic) WCStoryDataMgr *dataMgr; // @synthesize dataMgr=_dataMgr;
- (void).cxx_destruct;
- (void)showCameraTipsOnce;
- (_Bool)canShowCameraTips;
- (void)saveStorySetting;
- (void)loadStorySetting;
- (void)clearCameraRedDot;
- (_Bool)hasClearCameraRedDot;
- (_Bool)shouldShowCameraRedDot;
- (void)showBubbleTipsOnce;
- (_Bool)canShowBubbleTips;
- (void)onDiskStorageWarningCleanedSize:(unsigned long long *)arg1 subQueue:(id)arg2;
- (void)onDiskStorageWarningCleanedSize:(unsigned long long *)arg1;
- (void)onCommentFail:(id)arg1;
- (void)onCommentSuccess:(id)arg1;
- (void)onStoryPostSuccess:(id)arg1 LimitObj:(id)arg2;
- (void)onStoryPostFail:(id)arg1 ErrorType:(long long)arg2;
- (void)onStoryPostRetry:(id)arg1;
- (_Bool)RequestVideoDataByClientMediaID:(id)arg1 offset:(unsigned int)arg2 length:(unsigned int)arg3 durationSec:(unsigned int)arg4;
- (_Bool)IsVideoDataAvailableByClientMediaID:(id)arg1 offset:(unsigned int)arg2 length:(unsigned int)arg3;
- (_Bool)IsPreloadDownloadingWithMediaItem:(id)arg1;
- (_Bool)IsStreamDownloadingWithMediaItem:(id)arg1;
- (struct C2CDownloadResult)StopVideoDownloadWithMediaWrap:(id)arg1;
- (void)StartVideoDownloadWithMediaWrap:(id)arg1;
- (void)StartPreloadChatRoomVideoWithStoryDataItem:(id)arg1;
- (void)StartPreloadChatRoomVideoWithMediaItem:(id)arg1;
- (void)StartVideoPreloadWithItems:(id)arg1;
- (void)StartDownloadImageWithMediaItem:(id)arg1 Priority:(_Bool)arg2;
- (void)StartDownloadImageWithMediaItem:(id)arg1;
- (void)StartPreloadImageWithItems:(id)arg1;
- (id)getHistoryDateDetailWithDate:(id)arg1 timeZone:(int)arg2;
- (id)getHistoryPageIndexsWithTimeZone:(int)arg1 maxID:(unsigned long long)arg2 Limit:(unsigned int)arg3;
- (id)updateStoryUploadingStatus:(id)arg1;
- (void)uploadStoryDataItem:(id)arg1;
- (void)addStoryUnReadWithComment:(id)arg1;
- (void)makeAllCommentReadWithStoryItem:(id)arg1;
- (_Bool)hasUnReadStoryComments;
- (void)removeFailComment:(id)arg1;
- (id)getFailedComments;
- (void)addStoryComment:(id)arg1;
- (id)getLastReadUserStorysWithUserNames:(id)arg1;
- (double)getLastReadUserStoryTimeStamp:(id)arg1;
- (void)deleteStoryAndMakeUnReadTogetherWithTid:(id)arg1 UserName:(id)arg2;
- (_Bool)hasUnReadStoryWithUserName:(id)arg1;
- (void)makeStoryReadWithUserName:(id)arg1 Tid:(id)arg2;
- (void)addStorysFromSyncDataItems:(id)arg1;
- (double)getChatRoomNextSyncTimeStamp:(id)arg1;
- (id)getChatRoomSyncData:(id)arg1;
- (void)removeChatRoomStorySync:(id)arg1;
- (_Bool)shouldChatRoomSyncStory:(id)arg1;
- (void)addChatRoomSyncStoryWithChatName:(id)arg1 NextSyncTime:(unsigned int)arg2 Buffer:(id)arg3;
- (void)deleteStoryAllDataWithUserName:(id)arg1;
- (id)getChatRoomSycStorysWithUserName:(id)arg1;
- (void)updateStoryCommentsWithDataItem:(id)arg1;
- (id)getStoryDataItemWithTid:(id)arg1;
- (id)getStorysWithUserName:(id)arg1 MaxTid:(id)arg2;
- (id)getLocalAllStorysWithUserName:(id)arg1;
- (id)getLocalNewestStoryWithUserName:(id)arg1;
- (id)getMaxTidStoryWithUserName:(id)arg1;
- (unsigned long long)getLocalStoryCountWithUserName:(id)arg1;
- (void)deleteStoryDataItem:(id)arg1 retHandler:(CDUnknownBlockType)arg2;
- (void)fetchNewestStoryWithUserName:(id)arg1 MaxId:(unsigned long long)arg2 ChatRoomName:(id)arg3 DataHandler:(CDUnknownBlockType)arg4;
- (void)fetchStoryDateDetailWithDateString:(id)arg1 timeZone:(int)arg2 DataHandler:(CDUnknownBlockType)arg3;
- (void)fetchHistoryStoryWithTimeZone:(int)arg1 MaxId:(unsigned long long)arg2 DataHandler:(CDUnknownBlockType)arg3;
- (void)uploadRetry;
- (id)getPostLimitString;
- (_Bool)hasLocalStoryWithUserName:(id)arg1;
- (_Bool)shouldShowStory;
- (void)onServiceClearData;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

