//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMSightCameraViewController.h"

@class UIButton, WCTransitionUnit;

@interface WCStoryCameraViewController : MMSightCameraViewController
{
    struct CGPoint _panGestureBeginPoint;
    _Bool _shouldCloseWhenGestureEnd;
    struct CGPoint _panGestureLastPosition;
    double _panGestureAnimationDuration;
    _Bool _hasBeginDrag;
    _Bool _shouldIgnoreDrag;
    _Bool _isLongPressHandled;
    int _panDirectionFactor;
    UIButton *_albumBtn;
    _Bool _shouldDismissPreview;
    _Bool _showTeachView;
    CDUnknownBlockType _takenCompletion;
    CDUnknownBlockType _willQuitBlock;
    unsigned long long _transitionType;
    WCTransitionUnit *_transitionUnit;
    struct CGPoint _startAnimationPoint;
    struct CGRect _resultAnimationRect;
}

@property(retain, nonatomic) WCTransitionUnit *transitionUnit; // @synthesize transitionUnit=_transitionUnit;
@property(nonatomic) _Bool showTeachView; // @synthesize showTeachView=_showTeachView;
@property(nonatomic) unsigned long long transitionType; // @synthesize transitionType=_transitionType;
@property(copy, nonatomic) CDUnknownBlockType willQuitBlock; // @synthesize willQuitBlock=_willQuitBlock;
@property(copy, nonatomic) CDUnknownBlockType takenCompletion; // @synthesize takenCompletion=_takenCompletion;
@property(nonatomic) struct CGRect resultAnimationRect; // @synthesize resultAnimationRect=_resultAnimationRect;
@property(nonatomic) struct CGPoint startAnimationPoint; // @synthesize startAnimationPoint=_startAnimationPoint;
@property(nonatomic) _Bool shouldDismissPreview; // @synthesize shouldDismissPreview=_shouldDismissPreview;
- (void).cxx_destruct;
- (void)changeCameraCaptureSessionToRun:(_Bool)arg1;
- (void)DismissMyselfAnimated:(_Bool)arg1;
- (void)closeAfterDone;
- (void)showImagePicker;
- (_Bool)useTransparentNavibar;
- (void)viewDidPresent:(_Bool)arg1;
- (void)viewDidPush:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

