//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSXMLParserDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSString, NSXMLParser, WCSVGCanvas, WCSVGStyledPathFactory;

@interface WCSVGParser : NSObject <NSXMLParserDelegate>
{
    _Bool _isDefined;
    WCSVGCanvas *_rootCanvas;
    NSXMLParser *_xmlParser;
    WCSVGStyledPathFactory *_pathFactory;
    NSMutableArray *_currentCanvasStack;
    NSMutableDictionary *_maskCanvases;
    unsigned long long _groupLevel;
    NSMutableDictionary *_groupTransforms;
    NSMutableDictionary *_groupAppearances;
    struct CGRect _viewBox;
}

@property(nonatomic) _Bool isDefined; // @synthesize isDefined=_isDefined;
@property(retain, nonatomic) NSMutableDictionary *groupAppearances; // @synthesize groupAppearances=_groupAppearances;
@property(retain, nonatomic) NSMutableDictionary *groupTransforms; // @synthesize groupTransforms=_groupTransforms;
@property unsigned long long groupLevel; // @synthesize groupLevel=_groupLevel;
@property(retain, nonatomic) NSMutableDictionary *maskCanvases; // @synthesize maskCanvases=_maskCanvases;
@property(retain, nonatomic) NSMutableArray *currentCanvasStack; // @synthesize currentCanvasStack=_currentCanvasStack;
@property(retain, nonatomic) WCSVGStyledPathFactory *pathFactory; // @synthesize pathFactory=_pathFactory;
@property(retain, nonatomic) NSXMLParser *xmlParser; // @synthesize xmlParser=_xmlParser;
@property(retain, nonatomic) WCSVGCanvas *rootCanvas; // @synthesize rootCanvas=_rootCanvas;
@property(nonatomic) struct CGRect viewBox; // @synthesize viewBox=_viewBox;
- (void).cxx_destruct;
- (id)currentCanvas;
- (void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;
- (void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;
- (_Bool)parseSVGDocument;
- (id)initWithSVGData:(id)arg1;
- (id)initWithSVGDocument:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

