//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WCUpdateBootsUtil : NSObject
{
}

+ (void)reportIDKeyData:(unsigned int)arg1 key:(unsigned int)arg2 value:(unsigned int)arg3;
+ (id)getWeChatUUID;
+ (id)getPatchDataFilePath;
+ (id)getPatchInfoFilePath;
+ (id)getPatchDir;
+ (id)getDirOfPatchBoots;

@end

