//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface WebSearchCgiUserInfo : MMObject
{
    NSString *_requestId;
    NSString *_tagId;
    NSString *_subSessionId;
    NSString *_widgetId;
}

@property(retain, nonatomic) NSString *widgetId; // @synthesize widgetId=_widgetId;
@property(retain, nonatomic) NSString *subSessionId; // @synthesize subSessionId=_subSessionId;
@property(retain, nonatomic) NSString *tagId; // @synthesize tagId=_tagId;
@property(retain, nonatomic) NSString *requestId; // @synthesize requestId=_requestId;
- (void).cxx_destruct;

@end

