//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WebviewJSEventHandlerBase.h"

@class WebRecordDB;

@interface WebviewJSEventHandler_recordHistory : WebviewJSEventHandlerBase
{
    WebRecordDB *_db;
}

@property(retain, nonatomic) WebRecordDB *db; // @synthesize db=_db;
- (void).cxx_destruct;
- (void)handleJSEvent:(id)arg1 HandlerFacade:(id)arg2 ExtraData:(id)arg3;

@end

