//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextViewDelegate.h"

@protocol WNParaTextViewDelegate <UITextViewDelegate>

@optional
- (void)onWNTextViewAttrTextChanged;
- (_Bool)isTextViewMenuEnable;
- (void)onTextViewTouched:(long long)arg1;
- (void)onTextViewMenuPaste;
- (void)onSelectAll;
- (void)onSelectText:(struct _NSRange)arg1;
@end

