//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray;

@interface WSDotLoadingView : UIView
{
    NSMutableArray *_dots;
    _Bool _animating;
    struct CGSize _dotSize;
}

- (void).cxx_destruct;
- (void)stopLoading;
- (void)startLoading;
- (_Bool)isDotAnimationRemoved;
- (id)fadeInAnimation:(double)arg1;
- (void)setDetachDistance:(double)arg1;
- (void)resetPos;
- (void)ensureDotsPathCreated;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

