//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MMHeadImageView, MMUILabel, NSArray, NSMutableArray;

@interface WSVideoHeadLabelView : UIView
{
    NSMutableArray *_arrHeadImageView;
    MMHeadImageView *_selfHeadImageView;
    _Bool _isLikeBySelf;
    unsigned int _uiMaxHeadImgCount;
    MMUILabel *_label;
    NSArray *_arrUsername;
}

@property(retain, nonatomic) NSArray *arrUsername; // @synthesize arrUsername=_arrUsername;
@property(nonatomic) _Bool isLikeBySelf; // @synthesize isLikeBySelf=_isLikeBySelf;
@property(readonly, nonatomic) MMUILabel *label; // @synthesize label=_label;
@property(nonatomic) unsigned int uiMaxHeadImgCount; // @synthesize uiMaxHeadImgCount=_uiMaxHeadImgCount;
- (void).cxx_destruct;
- (void)layoutSubViews;
- (void)layoutWidthToFit;
- (void)resetHeadView;
- (id)makeHeadImageViewByUsr:(id)arg1;
- (void)updateHeadView;
- (void)initViews;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

