//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, NSMutableDictionary;

@interface WSWebRecommendTabsView : UIView
{
    id <WSWebRecommendTabsViewDelegate> _delegate;
    UIView *_tabUnderLine;
    NSMutableArray *_tabButtons;
    NSMutableDictionary *_reddotStatusDic;
}

@property(retain, nonatomic) NSMutableDictionary *reddotStatusDic; // @synthesize reddotStatusDic=_reddotStatusDic;
@property(retain, nonatomic) NSMutableArray *tabButtons; // @synthesize tabButtons=_tabButtons;
@property(retain, nonatomic) UIView *tabUnderLine; // @synthesize tabUnderLine=_tabUnderLine;
@property(nonatomic) __weak id <WSWebRecommendTabsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)outsideGetTabsReddotInfoDic;
- (void)configContentReddot:(_Bool)arg1 numberReddot:(long long)arg2 withCategory:(long long)arg3;
- (void)tabButtonSelected:(id)arg1 index:(long long)arg2 byClicked:(_Bool)arg3;
- (void)tabButtonClicked:(id)arg1;
- (void)updateTabButtonState:(long long)arg1 needAnim:(_Bool)arg2;
- (void)outsideCallTabSelected:(long long)arg1;
- (long long)outsideCallTabSelectedWithCategory:(long long)arg1;
- (_Bool)configTabList:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

